# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: batch/v1
kind: Job
metadata:
  name: dsv4-bench
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 43200
  template:
    spec:
      priorityClassName: ci-nightly-high-priority
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - key: dedicated
        operator: Equal
        value: user-workload
        effect: NoExecute
      containers:
      - name: bench
        env:
        - name: ENDPOINT
          value: dsv4-pro-agg-frontend:8000
        - name: CONCURRENCIES
          value: "1 8 64 128 256 512 1024"
      volumes:
      - name: model-cache
        persistentVolumeClaim:
          claimName: shared-model-cache
