/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * ReleaseSupportMatrix — human-facing release compatibility log for the
 * Compatibility reference page. Lists every stable release and patch,
 * grouped by minor line, one table per line: a release's backends sit on
 * adjacent rows under a single rowspan'd release cell.
 *
 * Every row is derived from CUDA_HISTORY and RELEASES in releases.data.ts;
 * nothing is transcribed or duplicated here. The Compatibility page's
 * <llms-only> twin (generated by scripts/gen_llms_tables.py) carries the
 * same rows as a flat markdown table so agent-facing exports never lose
 * the matrix; this component is deliberately the human-only rendering.
 *
 * The table itself is deliberately unstyled -- it inherits the docs theme's
 * table typography and matches every other table on the page. The only CSS
 * here dresses the minor-line disclosure rows and the release cell, because
 * a bare <summary> gives no click target and no open/closed affordance. An
 * earlier revision rendered bordered cards from ~250 lines of .dynref-rsm-*
 * rules and read as a separate widget bolted onto the page; this is the
 * smaller treatment that keeps the rows legible without that.
 *
 * CSS is injected via dangerouslySetInnerHTML, not as a <style> text child:
 * a text child is escaped on render, which turns any `>` child combinator
 * into &gt; and silently drops the rule (see #12402).
 *
 * Server component (no "use client"); minor lines use native
 * <details>/<summary> for progressive disclosure, so no client JS is
 * required.
 */

import {
  RELEASES,
  CUDA_HISTORY,
  CUDA_NOTES,
  type CudaRow,
  type Release,
} from "./releases.data";

// Only stable and patch releases carry CUDA_HISTORY rows and belong in the
// support matrix. Platform previews and model-specific builds are excluded;
// CUDA_NOTES calls out the ones whose toolkit support differs, and the
// machine-readable releases page carries the full inventory.
/* Just enough to make each minor line read as a disclosure row: a rule
 * between lines, a target big enough to click, and a marker that turns. The
 * table inside stays the theme's own -- this is deliberately not the bordered
 * card treatment an earlier revision carried. */
const RSM_CSS = `
.dynref-rsm-line {
    border-bottom: 1px solid var(--border, var(--grayscale-a5));
}

.dynref-rsm-line[open] {
    padding-bottom: 14px;
}

.dynref-rsm-summary {
    display: flex;
    flex-wrap: wrap;
    align-items: baseline;
    gap: 4px 10px;
    padding: 9px 6px;
    border-radius: 6px;
    cursor: pointer;
    list-style: none;
}

.dynref-rsm-summary::-webkit-details-marker { display: none; }

.dynref-rsm-summary::before {
    content: "›";
    display: inline-block;
    width: 10px;
    color: var(--pst-color-text-muted);
    font-size: 15px;
    line-height: 1;
    transition: transform 120ms ease;
}

.dynref-rsm-line[open] > .dynref-rsm-summary::before {
    transform: rotate(90deg);
}

.dynref-rsm-summary:hover { background: rgba(118, 185, 0, 0.06); }
.dark .dynref-rsm-summary:hover { background: rgba(118, 185, 0, 0.10); }

.dynref-rsm-summary:focus-visible {
    outline: 2px solid var(--nv-color-green, #76B900);
    outline-offset: -2px;
}

.dynref-rsm-minor {
    font-weight: 700;
    font-variant-numeric: tabular-nums;
}

.dynref-rsm-meta {
    color: var(--pst-color-text-muted);
    font-size: 12.5px;
}

.dynref-rsm-cudas { margin-left: auto; }

/* The release cell stacks version over kind/date/UCX; without this the small
 * lines crowd the version and the row loses its anchor. */
.dynref-rsm-release-version {
    display: block;
    font-variant-numeric: tabular-nums;
}

.dynref-rsm-release-meta {
    display: block;
    margin-top: 3px;
    color: var(--pst-color-text-muted);
    font-size: 11.5px;
    font-weight: 400;
    line-height: 1.5;
}

@media (max-width: 640px) {
    .dynref-rsm-cudas { margin-left: 0; }
}
`;


const SUPPORT_KINDS: ReadonlySet<Release["kind"]> = new Set(["stable", "patch"]);

// CUDA majors the matrix knows how to render, in display order. A toolkit
// whose leading integer sits outside this set fails the render rather than
// silently skipping the row -- the same fail-closed discipline the parser
// uses when releases.data.ts grows a construct it has not been taught yet.
const CUDA_MAJORS = ["12", "13"] as const;
type CudaMajor = (typeof CUDA_MAJORS)[number];

interface BackendCells {
  engineKey: "sglang" | "trtllm" | "vllm";
  nixlKey: "nixlSglang" | "nixlTrtllm" | "nixlVllm";
}

const BACKEND_PIN_KEYS: Record<CudaRow["backend"], BackendCells> = {
  SGLang: { engineKey: "sglang", nixlKey: "nixlSglang" },
  "TensorRT-LLM": { engineKey: "trtllm", nixlKey: "nixlTrtllm" },
  vLLM: { engineKey: "vllm", nixlKey: "nixlVllm" },
};

// Order backends take on a release that predates CUDA_HISTORY; matches the
// order CUDA_HISTORY itself lists them in.
const BACKEND_ORDER: readonly CudaRow["backend"][] = [
  "SGLang",
  "TensorRT-LLM",
  "vLLM",
];

// Printed where a release records no CUDA toolkit or driver floor at all.
const UNRECORDED = "Not recorded";

function cudaMajor(toolkit: string): CudaMajor {
  const major = toolkit.split(".", 1)[0];
  if (major === "12" || major === "13") return major;
  throw new Error(
    `ReleaseSupportMatrix: CUDA toolkit "${toolkit}" is outside the known ` +
      `majors ${CUDA_MAJORS.join(" / ")}; extend the component`,
  );
}

interface BackendLine {
  backend: CudaRow["backend"];
  engine?: string;
  toolkit: string;
  minDriver: string;
  nixl?: string;
  note?: string;
}

interface MajorBlock {
  major: CudaMajor;
  lines: BackendLine[];
}

interface ReleaseBlock {
  release: Release;
  version: string; // bare (no leading v)
  blocks: MajorBlock[]; // only majors that ship rows for this release
  postTrains: string[]; // bare versions inheriting this release's CUDA support
}

interface MinorGroup {
  minor: string; // e.g. "1.2.x"
  releases: ReleaseBlock[];
  majors: CudaMajor[]; // unique across all releases in the line, ordered
  releaseCount: number; // every stable/patch in the line, post trains included
}

function bareVersion(version: string): string {
  return version.startsWith("v") ? version.slice(1) : version;
}

function minorLine(version: string): string {
  const [major, minor] = version.split(".");
  if (!major || !minor) {
    throw new Error(`ReleaseSupportMatrix: cannot minor-group version ${version}`);
  }
  return `${major}.${minor}.x`;
}

/* '0.7.0.post1' -> '0.7.0'; anything else unchanged. Post trains republish
 * images or wheels off an existing release and carry no CUDA_HISTORY row --
 * CUDA_NOTES states they have the same CUDA support as their base. They are
 * therefore named in their base's release cell rather than given rows of
 * their own. */
function postTrainBase(version: string): string {
  const cut = version.indexOf(".post");
  return cut === -1 ? version : version.slice(0, cut);
}

function supportedReleases(): string[] {
  return RELEASES.filter((rel) => SUPPORT_KINDS.has(rel.kind)).map((rel) =>
    bareVersion(rel.version),
  );
}

function buildMajorBlock(
  release: Release,
  rows: CudaRow[],
  major: CudaMajor,
): MajorBlock {
  const pins = release.pins ?? {};
  const block: MajorBlock = { major, lines: [] };
  for (const row of rows) {
    if (cudaMajor(row.toolkit) !== major) continue;
    const keys = BACKEND_PIN_KEYS[row.backend];
    block.lines.push({
      backend: row.backend,
      engine: keys ? pins[keys.engineKey] : undefined,
      toolkit: row.toolkit,
      minDriver: row.minDriver,
      nixl: keys ? pins[keys.nixlKey] : undefined,
      note: row.note,
    });
  }
  return block;
}

/* A stable release or patch with no CUDA_HISTORY row still belongs on this
 * page -- v0.6.x shipped before the CUDA matrix was recorded. Falling back to
 * the engine and NIXL pins it does carry keeps the section's claim to list
 * every stable release and patch true; dropping the release would quietly
 * contradict it. */
function unrecordedLines(release: Release): BackendLine[] {
  const pins = release.pins ?? {};
  const lines: BackendLine[] = [];
  for (const backend of BACKEND_ORDER) {
    const keys = BACKEND_PIN_KEYS[backend];
    const engine = pins[keys.engineKey];
    if (!engine) continue;
    lines.push({
      backend,
      engine,
      toolkit: UNRECORDED,
      minDriver: UNRECORDED,
      nixl: pins[keys.nixlKey],
    });
  }
  return lines;
}

function buildReleaseBlock(
  version: string,
  release: Release,
  rows: CudaRow[],
  postTrains: string[],
): ReleaseBlock {
  const blocks: MajorBlock[] = [];
  for (const major of CUDA_MAJORS) {
    const block = buildMajorBlock(release, rows, major);
    if (block.lines.length > 0) blocks.push(block);
  }
  return { release, version, blocks, postTrains };
}

/* Driven by RELEASES, not CUDA_HISTORY: iterating the CUDA rows silently
 * dropped every stable/patch release with no row of its own (v0.6.0, v0.6.1,
 * v0.6.1.post1), which is precisely the set this page must not lose. */
function groupByMinorLine(): MinorGroup[] {
  const supported = supportedReleases();
  const groups = new Map<string, MinorGroup>();
  for (const release of RELEASES) {
    if (!SUPPORT_KINDS.has(release.kind)) continue;
    const version = bareVersion(release.version);
    // Post trains ride on their base's rows rather than getting their own.
    if (postTrainBase(version) !== version) continue;
    const line = minorLine(version);
    const versionRows = CUDA_HISTORY.filter((r) => r.version === version);
    const postTrains = supported.filter(
      (v) => v !== version && postTrainBase(v) === version,
    );
    const block = buildReleaseBlock(version, release, versionRows, postTrains);
    const group = groups.get(line) ?? {
      minor: line,
      releases: [],
      majors: [],
      // Counted from RELEASES, not from the rows: a post train shares its
      // base's rows, so counting rendered releases would report 0.8.x as two
      // releases when the line actually shipped five.
      releaseCount: supported.filter((v) => minorLine(v) === line).length,
    };
    group.releases.push(block);
    for (const b of block.blocks) {
      if (!group.majors.includes(b.major)) group.majors.push(b.major);
    }
    groups.set(line, group);
  }
  return Array.from(groups.values());
}

function kindLabel(kind: Release["kind"]): string {
  // The support matrix only lists stable/patch (SUPPORT_KINDS gate), so any
  // other kind reaching here is a data bug; print it rather than throwing so
  // the page still loads.
  return kind;
}

/* Flattened in CUDA_MAJORS order, so a release's rows read 12 before 13 and
 * the toolkit column stays monotonic down the block. */
function releaseLines(block: ReleaseBlock): BackendLine[] {
  const lines = block.blocks.flatMap((major) => major.lines);
  return lines.length > 0 ? lines : unrecordedLines(block.release);
}

function ReleaseMeta({ block }: { block: ReleaseBlock }) {
  const { release, postTrains } = block;
  return (
    <>
      <span className="dynref-rsm-release-version">v{block.version}</span>
      <span className="dynref-rsm-release-meta">
        {kindLabel(release.kind)}
        {release.date && ` · ${release.date}`}
        <br />
        UCX {release.ucx ?? "not specified"}
        {postTrains.length > 0 && (
          <>
            <br />
            Post train{postTrains.length === 1 ? "" : "s"} v
            {postTrains.join(", v")} share
            {postTrains.length === 1 ? "s" : ""} this CUDA support
          </>
        )}
      </span>
    </>
  );
}

function MinorLineTable({ group }: { group: MinorGroup }) {
  return (
    <table>
      <thead>
        <tr>
          <th>Release</th>
          <th>Backend</th>
          <th>Engine</th>
          <th>CUDA toolkit</th>
          {/* Per-backend, not per-release: within one CUDA major the backends
              can sit on different toolkits and therefore different driver
              floors (v0.7.1 pairs SGLang/12.8 with 570.xx+ and vLLM/12.9 with
              575.xx+), so the floor has to be readable on its own row. */}
          <th>Min driver</th>
          <th>NIXL</th>
          <th>Note</th>
        </tr>
      </thead>
      <tbody>
        {group.releases.map((block) => {
          const lines = releaseLines(block);
          return lines.map((line, index) => (
            <tr key={`${block.version}-${line.backend}-${line.toolkit}`}>
              {index === 0 && (
                <th rowSpan={lines.length} scope="rowgroup">
                  <ReleaseMeta block={block} />
                </th>
              )}
              <td>{line.backend}</td>
              <td>{line.engine ?? "—"}</td>
              <td>{line.toolkit}</td>
              <td>{line.minDriver}</td>
              <td>{line.nixl ?? "—"}</td>
              <td>{line.note ?? "—"}</td>
            </tr>
          ));
        })}
      </tbody>
    </table>
  );
}

export function ReleaseSupportMatrix() {
  const groups = groupByMinorLine();
  if (groups.length === 0) {
    throw new Error(
      "ReleaseSupportMatrix: RELEASES carries no stable or patch entry -- " +
        "the matrix would render empty",
    );
  }
  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: RSM_CSS }} />
      {groups.map((group, index) => (
        <details className="dynref-rsm-line" key={group.minor} open={index === 0}>
          <summary className="dynref-rsm-summary">
            <span className="dynref-rsm-minor">{group.minor}</span>
            <span className="dynref-rsm-meta">
              {group.releaseCount} release{group.releaseCount === 1 ? "" : "s"}
            </span>
            <span className="dynref-rsm-meta dynref-rsm-cudas">
              {group.majors.length > 0
                ? `CUDA ${group.majors.join(", ")}`
                : "CUDA not recorded"}
            </span>
          </summary>
          <MinorLineTable group={group} />
        </details>
      ))}
      <ul>
        {CUDA_NOTES.map((note) => (
          <li key={note}>
            <small>{note}</small>
          </li>
        ))}
      </ul>
    </>
  );
}
