all:
  - '**'

docs: &docs
  - 'docs/**'
  - '**/*.md'
  - '**/*.rst'
  - '**/*.txt'

ci: &ci
  - '.github/workflows/**'
  - '.github/filters.yaml'
  - '.github/actions/**'

# Will run tests for all 3 containers (vLLM, SGLang, TRTLLM)
core:
  - *ci
  - 'container/build.sh'
  - 'container/Dockerfile'
  - 'container/deps/*'
  - 'lib/**'
  - 'tests/**'
  - 'components/src/dynamo/router/**'
  - 'components/src/dynamo/mocker/**'
  - 'components/src/dynamo/frontend/**'
  - 'components/src/dynamo/common/**'
  - '*.toml'
  - '*.lock'
  - '*.py'
  - '*.rs'
  - '!**/*.md' # Avoid running on doc changes
  - '!**/*.rst' # Avoid running on doc changes
  - '!**/*.txt' # Avoid running on doc changes

operator:
  - *ci
  - 'deploy/cloud/operator/**'

deploy:
  - 'deploy/cloud/helm/**'
  - 'deploy/utils/**'

planner:
  - 'components/src/dynamo/planner/**'
  - 'tests/planner/**'

vllm: &vllm
  - 'container/Dockerfile.vllm'
  - 'container/deps/requirements.vllm.txt'
  - 'container/deps/vllm/**'
  - 'examples/backends/vllm/**'
  - 'components/src/dynamo/vllm/**'

sglang: &sglang
  - 'container/Dockerfile.sglang'
  - 'examples/backends/sglang/**'
  - 'components/src/dynamo/sglang/**'

trtllm: &trtllm
  - 'container/Dockerfile.trtllm'
  - 'examples/backends/trtllm/**'
  - 'components/src/dynamo/trtllm/**'
  - 'container/build_trtllm_wheel.sh'
