/*
 * SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dynamo

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"

	"github.com/ai-dynamo/dynamo/deploy/operator/api/v1alpha1"
	"github.com/ai-dynamo/dynamo/deploy/operator/api/v1beta1"
)

const dgdWorkerHashPlaceholderValue = "worker-hash-placeholder"

// ComputeLegacyAlphaDGDWorkersSpecHash returns the v1alpha1 worker hash that a
// pre-v1beta1 controller would compute for the DGD's current spec. Conversion
// must preserve every v1alpha1 hash input shape this depends on.
func ComputeLegacyAlphaDGDWorkersSpecHash(dgd *v1beta1.DynamoGraphDeployment) (string, error) {
	alpha := &v1alpha1.DynamoGraphDeployment{}
	if err := alpha.ConvertFrom(dgd); err != nil {
		return "", err
	}
	return v1alpha1.ComputeDGDWorkersSpecHash(alpha)
}

// ComputeDGDWorkersSpecHash computes the v2 worker hash from the worker DCDs
// generated by the same DGD-to-DCD path used by reconciliation. The active
// worker hash is replaced by a fixed placeholder before generation so the hash
// can be computed without depending on itself.
func ComputeDGDWorkersSpecHash(dgd *v1beta1.DynamoGraphDeployment) (string, error) {
	if dgd == nil {
		return "", fmt.Errorf("nil DynamoGraphDeployment")
	}

	dcds, err := GenerateDynamoComponentsDeployments(
		dgd,
		nil,
		nil,
		RollingUpdateContext{NewWorkerHash: dgdWorkerHashPlaceholderValue},
	)
	if err != nil {
		return "", err
	}

	type workerTemplate struct {
		Labels      map[string]string                     `json:"labels,omitempty"`
		Annotations map[string]string                     `json:"annotations,omitempty"`
		Spec        v1beta1.DynamoComponentDeploymentSpec `json:"spec"`
	}

	workerDCDs := make(map[string]workerTemplate, len(dcds))
	for _, dcd := range dcds {
		if dcd != nil && IsWorkerComponent(string(dcd.Spec.ComponentType)) {
			componentName := GetDCDComponentName(dcd)
			if componentName == "" {
				return "", fmt.Errorf("generated worker DCD %q has no component name label", dcd.Name)
			}
			if _, exists := workerDCDs[componentName]; exists {
				return "", fmt.Errorf("duplicate generated worker DCD component name %q", componentName)
			}
			workerDCDs[componentName] = workerTemplate{
				Labels:      GetDCDKubeLabels(dcd),
				Annotations: GetDCDKubeAnnotations(dcd),
				Spec:        workerHashSpec(dcd),
			}
		}
	}

	data, err := json.Marshal(workerDCDs)
	if err != nil {
		return "", fmt.Errorf("marshal generated worker DCDs: %w", err)
	}

	hash := sha256.Sum256(data)
	return hex.EncodeToString(hash[:])[:8], nil
}

func workerHashSpec(dcd *v1beta1.DynamoComponentDeployment) v1beta1.DynamoComponentDeploymentSpec {
	spec := dcd.Spec.DeepCopy()

	// Replica count, availability envelope, and autoscaling ownership patch the
	// active DCD. They must not create a new worker generation.
	spec.Replicas = nil
	spec.MinAvailable = nil
	spec.ScalingAdapter = nil

	return *spec
}
