# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: q32b-1p1d-cloud-provider
spec:
  services:
    PrefillWorker:
      extraPodSpec:
        mainContainer:
          env: &nscaleEnvironment
            - name: GPU_MEMORY_UTILIZATION
              value: "0.70"
    DecodeWorker:
      extraPodSpec:
        mainContainer:
          env: *nscaleEnvironment
