# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
source: kustomize/base
nameTemplate: "${variant}"
matrix:
  variant:
    - name: generic
      components: []
