# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: q32b-1p1d-cloud-provider
spec:
  services:
    PrefillWorker:
      extraPodSpec:
        mainContainer:
          image: &vllmEfaImage nvcr.io/nvidia/ai-dynamo/vllm-runtime:1.1.1-efa-amd64
    DecodeWorker:
      extraPodSpec:
        mainContainer:
          image: *vllmEfaImage
