# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "aisimulate-python"
description = "Python binding for the AISimulate native replay runtime"
version = "0.1.0-dev.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lib]
name = "_runtime"
crate-type = ["cdylib", "rlib"]

[features]
extension-module = ["pyo3/extension-module"]

[dependencies]
aisimulate-core = { workspace = true }
anyhow = { workspace = true }
pyo3 = { version = "0.23.4", features = ["abi3-py310"] }
serde = { workspace = true }
serde_json = { workspace = true }
