# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: vllm-disagg-nebius-ib
spec:
  services:
    DecodeWorker:
      extraPodSpec:
        mainContainer:
          env:
            - name: UCX_RNDV_THRESH
              value: "8192"
