# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: disagg-workers
spec:
  services:
    PrefillWorker:
      extraPodSpec:
        mainContainer:
          env: &efaEnvironment
            - name: DYN_KVBM_NIXL_BACKEND_LIBFABRIC
              value: "true"
            - name: DYN_KVBM_NIXL_BACKEND_UCX
              value: "false"
            - name: FI_PROVIDER
              value: efa
            - name: FI_EFA_USE_DEVICE_RDMA
              value: "1"
            - name: FI_EFA_ENABLE_SHM_TRANSFER
              value: "0"
            - name: FI_LOG_LEVEL
              value: warn
    DecodeWorker:
      extraPodSpec:
        mainContainer:
          env: *efaEnvironment
