#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate, render, and compose Kustomize recipe variants."""

from __future__ import annotations

import argparse
import itertools
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, TypeAlias

import yaml

SPDX_HEADER = (
    "# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.\n"
    "# SPDX-License-Identifier: Apache-2.0"
)
REPO_ROOT = Path(__file__).resolve().parents[1]
OPENAPI_GENERATOR = REPO_ROOT / "scripts/generate_kustomize_openapi.py"
KUSTOMIZATION_FILE = "kustomization.yaml"
GENERATED_OVERLAY_PREFIX = "# Regenerate: scripts/kustomize-matrix.py unfold "
GENERATED_MANIFEST_PREFIX = "#   scripts/kustomize-matrix.py render "
LEGACY_GENERATED_OVERLAY_PREFIX = "# Generated by: scripts/kustomize-matrix.py unfold "
LEGACY_GENERATED_MANIFEST_PREFIX = (
    "# To update the checked-in recipe: scripts/kustomize-matrix.py render "
)
LEGACY_MATRIX_RENDER_COMMAND_PREFIX = (
    "# Regenerate: scripts/kustomize-matrix.py render "
)
PathPart: TypeAlias = str | int
YamlPath: TypeAlias = tuple[PathPart, ...]
FIRST_TOP_LEVEL_KEYS = ("apiVersion", "kind", "metadata")
NAME_PATTERN = re.compile(r"[A-Za-z0-9][A-Za-z0-9._-]*\Z")
TEMPLATE_PATTERN = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")


@dataclass(frozen=True)
class MatrixValue:
    name: str
    components: tuple[Path, ...]


@dataclass(frozen=True)
class MatrixVariant:
    name: str
    components: tuple[Path, ...]


@dataclass(frozen=True)
class MatrixConfig:
    path: Path
    source: Path
    name_template: str
    dimensions: tuple[tuple[str, tuple[MatrixValue, ...]], ...]

    @property
    def recipe_root(self) -> Path:
        return self.path.parent

    @property
    def overlays_dir(self) -> Path:
        return self.recipe_root / "kustomize/overlays"

    @property
    def command_path(self) -> str:
        return display_path(self.path)


@dataclass(frozen=True)
class DocumentId:
    api_version: str
    kind: str
    name: str


@dataclass
class CommentBlock:
    doc_id: DocumentId
    path: YamlPath
    lines: list[str]


@dataclass
class DocumentScan:
    doc_id: DocumentId | None
    comments: list[CommentBlock]
    targets: dict[YamlPath, int]


@dataclass
class TopLevelBlock:
    key: str | None
    lines: list[str]


def display_path(path: Path) -> str:
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def kustomize_command() -> list[str]:
    if shutil.which("kustomize"):
        return ["kustomize", "build"]
    if shutil.which("kubectl"):
        return ["kubectl", "kustomize"]
    raise RuntimeError("install kustomize or kubectl to build a Kustomization")


def load_yaml_mapping(path: Path) -> dict[str, Any]:
    try:
        value = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ValueError(f"invalid YAML in {display_path(path)}: {exc}") from exc
    if not isinstance(value, dict):
        raise TypeError(f"expected a YAML mapping in {display_path(path)}")
    return value


def require_string(value: Any, context: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{context} must be a non-empty string")
    return value


def resolve_component_paths(
    values: Any, matrix_path: Path, context: str
) -> tuple[Path, ...]:
    if not isinstance(values, list) or not all(
        isinstance(value, str) for value in values
    ):
        raise ValueError(f"{context} must be a list of component paths")

    components = tuple((matrix_path.parent / value).resolve() for value in values)
    for component in components:
        if not component.is_dir():
            raise ValueError(
                f"Kustomize Component is not a directory: {display_path(component)}"
            )
    return components


def load_matrix(path: str) -> MatrixConfig:
    matrix_path = Path(path).resolve()
    if not matrix_path.is_file():
        raise ValueError(f"matrix file does not exist: {path}")

    data = load_yaml_mapping(matrix_path)
    unknown_keys = set(data) - {"source", "nameTemplate", "matrix"}
    if unknown_keys:
        raise ValueError(
            f"unsupported matrix key in {display_path(matrix_path)}: {min(unknown_keys)}"
        )

    source_value = require_string(data.get("source"), "source")
    source = (matrix_path.parent / source_value).resolve()
    if not source.is_dir():
        raise ValueError(f"Kustomize source is not a directory: {source_value}")

    name_template = require_string(data.get("nameTemplate"), "nameTemplate")
    raw_matrix = data.get("matrix")
    if not isinstance(raw_matrix, dict) or not raw_matrix:
        raise ValueError("matrix must be a non-empty mapping of dimensions")

    dimensions: list[tuple[str, tuple[MatrixValue, ...]]] = []
    for dimension, raw_values in raw_matrix.items():
        if not isinstance(dimension, str) or not TEMPLATE_PATTERN.fullmatch(
            f"${{{dimension}}}"
        ):
            raise ValueError(f"invalid matrix dimension name: {dimension!r}")
        if not isinstance(raw_values, list) or not raw_values:
            raise ValueError(
                f"matrix dimension {dimension!r} must contain at least one value"
            )

        values: list[MatrixValue] = []
        value_names: set[str] = set()
        for index, raw_value in enumerate(raw_values):
            context = f"matrix.{dimension}[{index}]"
            if not isinstance(raw_value, dict):
                raise TypeError(f"{context} must be a mapping")
            unknown_value_keys = set(raw_value) - {"name", "components"}
            if unknown_value_keys:
                raise ValueError(
                    f"unsupported key in {context}: {min(unknown_value_keys)}"
                )
            name = require_string(raw_value.get("name"), f"{context}.name")
            if not NAME_PATTERN.fullmatch(name):
                raise ValueError(
                    f"{context}.name is not a valid variant name: {name!r}"
                )
            if name in value_names:
                raise ValueError(
                    f"matrix dimension {dimension!r} repeats value {name!r}"
                )
            value_names.add(name)
            values.append(
                MatrixValue(
                    name=name,
                    components=resolve_component_paths(
                        raw_value.get("components"),
                        matrix_path,
                        f"{context}.components",
                    ),
                )
            )
        dimensions.append((dimension, tuple(values)))

    template_dimensions = set(TEMPLATE_PATTERN.findall(name_template))
    unknown_template_dimensions = template_dimensions - {name for name, _ in dimensions}
    if unknown_template_dimensions:
        raise ValueError(
            "nameTemplate references unknown dimension: "
            f"{min(unknown_template_dimensions)}"
        )
    if not template_dimensions:
        raise ValueError("nameTemplate must reference at least one matrix dimension")

    return MatrixConfig(
        path=matrix_path,
        source=source,
        name_template=name_template,
        dimensions=tuple(dimensions),
    )


def expand_matrix(config: MatrixConfig) -> list[MatrixVariant]:
    variants: list[MatrixVariant] = []
    names: set[str] = set()
    value_lists = [values for _, values in config.dimensions]
    dimension_names = [name for name, _ in config.dimensions]

    for values in itertools.product(*value_lists):
        replacements = dict(
            zip(dimension_names, (value.name for value in values), strict=True)
        )
        name = TEMPLATE_PATTERN.sub(
            lambda match, replacements=replacements: replacements[match.group(1)],
            config.name_template,
        )
        if not NAME_PATTERN.fullmatch(name):
            raise ValueError(
                f"nameTemplate generated an invalid variant name: {name!r}"
            )
        if name in names:
            raise ValueError(
                f"nameTemplate generated duplicate variant name {name!r}; include every varying dimension"
            )
        names.add(name)

        components = tuple(
            component for value in values for component in value.components
        )
        if len(set(components)) != len(components):
            raise ValueError(
                f"variant {name!r} selects the same Component more than once"
            )
        variants.append(MatrixVariant(name=name, components=components))

    return variants


def relative_path(path: Path, root: Path) -> str:
    return os.path.relpath(path, root)


def overlay_path(config: MatrixConfig, variant: MatrixVariant) -> Path:
    return config.overlays_dir / variant.name


def unfolded_kustomization(config: MatrixConfig, variant: MatrixVariant) -> str:
    overlay_dir = overlay_path(config, variant)
    lines = [
        SPDX_HEADER,
        "",
        "# Generated file. Do not edit this checked-in copy.",
        f"{GENERATED_OVERLAY_PREFIX}{config.command_path}",
        "",
        "apiVersion: kustomize.config.k8s.io/v1beta1",
        "kind: Kustomization",
        "sortOptions:",
        "  order: fifo",
        "resources:",
        f"  - {json.dumps(relative_path(config.source, overlay_dir))}",
    ]
    if variant.components:
        lines.append("components:")
        lines.extend(
            f"  - {json.dumps(relative_path(component, overlay_dir))}"
            for component in variant.components
        )
    return "\n".join(lines) + "\n"


def generated_overlay_paths(config: MatrixConfig) -> set[Path]:
    if not config.overlays_dir.exists():
        return set()
    generated: set[Path] = set()
    for path in config.overlays_dir.iterdir():
        kustomization = path / KUSTOMIZATION_FILE
        if not path.is_dir() or not kustomization.exists():
            continue
        content = kustomization.read_text(encoding="utf-8")
        if (
            GENERATED_OVERLAY_PREFIX in content
            or LEGACY_GENERATED_OVERLAY_PREFIX in content
        ):
            generated.add(path)
    return generated


def is_current_generated_overlay(config: MatrixConfig, path: Path) -> bool:
    marker = f"{GENERATED_OVERLAY_PREFIX}{config.command_path}"
    return marker in (path / KUSTOMIZATION_FILE).read_text(encoding="utf-8")


def unfold_matrix(
    config: MatrixConfig, *, check: bool, clean: bool = False
) -> list[Path]:
    expected = {
        overlay_path(config, variant): unfolded_kustomization(config, variant)
        for variant in expand_matrix(config)
    }
    stale: list[Path] = []
    for path, content in expected.items():
        kustomization = path / KUSTOMIZATION_FILE
        current = (
            kustomization.read_text(encoding="utf-8")
            if kustomization.exists()
            else None
        )
        if current != content:
            stale.append(kustomization)
            if not check:
                path.mkdir(parents=True, exist_ok=True)
                kustomization.write_text(content, encoding="utf-8")

    for path in generated_overlay_paths(config) - set(expected):
        kustomization = path / KUSTOMIZATION_FILE
        stale.append(kustomization)
        if not check and (clean or is_current_generated_overlay(config, path)):
            kustomization.unlink()
            try:
                path.rmdir()
            except OSError:
                pass
    return stale


def generate_kustomize_openapi(*, check: bool) -> None:
    command = [sys.executable, str(OPENAPI_GENERATOR)]
    if check:
        command.append("--check")
    result = subprocess.run(
        command, cwd=REPO_ROOT, check=False, capture_output=True, text=True
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip())


def starts_block_scalar(stripped_line: str) -> bool:
    if not stripped_line or stripped_line.startswith("#"):
        return False
    value = stripped_line.split("#", 1)[0].rstrip().rsplit(maxsplit=1)[-1]
    return value.startswith(("|", ">"))


def line_indent(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def parse_key_value(content: str) -> tuple[str, str] | None:
    if ":" not in content:
        return None
    key, value = content.split(":", 1)
    key = key.strip().strip("\"'")
    return (key, value.strip()) if key else None


def strip_inline_comment(value: str) -> str:
    return value.split("#", 1)[0].strip()


def scalar_value(value: str) -> str:
    return strip_inline_comment(value).strip("\"'")


def record_scalar(values: dict[YamlPath, str], path: YamlPath, value: str) -> None:
    value = scalar_value(value)
    if value:
        values[path] = value


def starts_nested_value(value: str, line: str) -> bool:
    stripped = strip_inline_comment(value)
    return not stripped or stripped.startswith(("&", "!")) or starts_block_scalar(line)


def scan_yaml(text: str) -> list[DocumentScan]:
    """Map YAML comments to fields without interpreting patch semantics."""

    docs: list[DocumentScan] = []
    comments: list[tuple[YamlPath, list[str]]] = []
    targets: dict[YamlPath, int] = {}
    values: dict[YamlPath, str] = {}
    stack: list[tuple[int, YamlPath]] = []
    sequence_indexes: dict[tuple[YamlPath, int], int] = {}
    pending_comments: list[str] = []
    block_scalar_indent: int | None = None

    def finish_document() -> None:
        nonlocal comments, targets, values, stack, sequence_indexes, pending_comments
        api_version = values.get(("apiVersion",))
        kind = values.get(("kind",))
        name = values.get(("metadata", "name"))
        doc_id = (
            DocumentId(api_version, kind, name)
            if api_version and kind and name
            else None
        )
        docs.append(
            DocumentScan(
                doc_id=doc_id,
                comments=[CommentBlock(doc_id, path, lines) for path, lines in comments]
                if doc_id
                else [],
                targets=targets,
            )
        )
        comments = []
        targets = {}
        values = {}
        stack = []
        sequence_indexes = {}
        pending_comments = []

    for line_number, line in enumerate(text.splitlines()):
        stripped = line.strip()
        indent = line_indent(line)
        if stripped == "---":
            finish_document()
            block_scalar_indent = None
            continue
        if block_scalar_indent is not None:
            if not stripped:
                continue
            if indent > block_scalar_indent:
                continue
            block_scalar_indent = None
        if starts_block_scalar(stripped):
            block_scalar_indent = indent
        if not stripped:
            continue
        if stripped.startswith("#"):
            if not stripped.startswith("# SPDX-"):
                pending_comments.append(stripped)
            continue

        if stripped.startswith("- "):
            while stack and indent < stack[-1][0]:
                stack.pop()
            while (
                stack and indent == stack[-1][0] and isinstance(stack[-1][1][-1], int)
            ):
                stack.pop()
        else:
            while stack and indent <= stack[-1][0]:
                stack.pop()
        parent_path = stack[-1][1] if stack else ()
        line_paths: list[YamlPath] = []
        comment_path: YamlPath | None = None
        if stripped.startswith("- "):
            sequence_key = (parent_path, indent)
            item_index = sequence_indexes.get(sequence_key, 0)
            sequence_indexes[sequence_key] = item_index + 1
            item_path = (*parent_path, item_index)
            line_paths.append(item_path)
            content = stripped[2:].strip()
            parsed = parse_key_value(content)
            if parsed:
                key, value = parsed
                key_path = (*item_path, key)
                line_paths.append(key_path)
                record_scalar(values, key_path, value)
                if key == "name" and (name := scalar_value(value)):
                    comment_path = (*parent_path, f"name={name}")
                    line_paths.append(comment_path)
                if starts_nested_value(value, content):
                    stack.append((indent, key_path))
                else:
                    stack.append((indent, item_path))
            else:
                stack.append((indent, item_path))
        else:
            parsed = parse_key_value(stripped)
            if not parsed:
                continue
            key, value = parsed
            key_path = (*parent_path, key)
            line_paths.append(key_path)
            record_scalar(values, key_path, value)
            if starts_nested_value(value, stripped):
                stack.append((indent, key_path))
        for item_path in line_paths:
            targets.setdefault(item_path, line_number)
        if pending_comments and line_paths:
            comments.append((comment_path or line_paths[0], pending_comments))
            pending_comments = []
    finish_document()
    return docs


def source_comment_paths(kustomization_dir: Path) -> list[Path]:
    """Find YAML sources from resources and Components, including nested parents."""

    source_paths: set[Path] = set()
    visited: set[Path] = set()

    def visit(directory: Path) -> None:
        directory = directory.resolve()
        if directory in visited:
            return
        visited.add(directory)
        kustomization_path = directory / KUSTOMIZATION_FILE
        if not kustomization_path.exists():
            return
        for pattern in ("*.yaml", "*.yml"):
            source_paths.update(
                path
                for path in directory.rglob(pattern)
                if path.name != KUSTOMIZATION_FILE
            )
        data = load_yaml_mapping(kustomization_path)
        for key in ("resources", "components"):
            for reference in data.get(key, []):
                if not isinstance(reference, str) or "://" in reference:
                    continue
                reference_path = (directory / reference).resolve()
                if reference_path.is_dir():
                    visit(reference_path)
                elif reference_path.suffix in {".yaml", ".yml"}:
                    source_paths.add(reference_path)

    visit(kustomization_dir)
    return sorted(source_paths)


def restore_source_comments(rendered: str, overlay_dir: Path) -> str:
    lines = rendered.splitlines()
    rendered_documents = [doc for doc in scan_yaml(rendered) if doc.doc_id is not None]
    documents_by_id = {doc.doc_id: doc for doc in rendered_documents}
    documents_by_gvk: dict[tuple[str, str], list[DocumentScan]] = {}
    for document in rendered_documents:
        assert document.doc_id is not None
        documents_by_gvk.setdefault(
            (document.doc_id.api_version, document.doc_id.kind), []
        ).append(document)

    def target_document(source_id: DocumentId) -> DocumentScan | None:
        if document := documents_by_id.get(source_id):
            return document
        candidates = documents_by_gvk.get((source_id.api_version, source_id.kind), [])
        return candidates[0] if len(candidates) == 1 else None

    insertions: dict[int, list[str]] = {}
    for source_path in source_comment_paths(overlay_dir):
        for document in scan_yaml(source_path.read_text(encoding="utf-8")):
            for block in document.comments:
                target = target_document(block.doc_id)
                line_number = target.targets.get(block.path) if target else None
                if line_number is None:
                    continue
                indent = " " * line_indent(lines[line_number])
                insertions.setdefault(line_number, []).extend(
                    f"{indent}{line}" for line in block.lines
                )
    restored: list[str] = []
    for line_number, line in enumerate(lines):
        restored.extend(insertions.get(line_number, []))
        restored.append(line)
    return "\n".join(restored) + "\n"


def reorder_rendered_top_level_fields(rendered: str) -> str:
    documents = [document.splitlines() for document in rendered.split("\n---\n")]
    reordered_documents: list[str] = []
    for document in documents:
        blocks: list[TopLevelBlock] = []
        current = TopLevelBlock(key=None, lines=[])
        for line in document:
            parsed = parse_key_value(line.strip()) if line_indent(line) == 0 else None
            key = parsed[0] if parsed and not line.lstrip().startswith("- ") else None
            if key is not None:
                if current.lines:
                    blocks.append(current)
                current = TopLevelBlock(key=key, lines=[line])
            else:
                current.lines.append(line)
        if current.lines:
            blocks.append(current)
        ordered = [
            block
            for key in FIRST_TOP_LEVEL_KEYS
            for block in blocks
            if block.key == key
        ]
        ordered.extend(
            block for block in blocks if block.key not in FIRST_TOP_LEVEL_KEYS
        )
        reordered_documents.append(
            "\n".join(line for block in ordered for line in block.lines).rstrip()
        )
    return "\n---\n".join(reordered_documents).rstrip() + "\n"


def rendered_header(config: MatrixConfig, overlay_dir: Path) -> str:
    return "\n".join(
        [
            "# Generated file. For repository contributors, do not edit this checked-in copy.",
            "# Regenerate every public overlay and rendered manifest of this matrix (from the repository root):",
            f"#   scripts/kustomize-matrix.py unfold {config.command_path}",
            f"{GENERATED_MANIFEST_PREFIX}{config.command_path}",
            "# Inspect only this Kustomize overlay (from the repository root):",
            f"#   kustomize build {display_path(overlay_dir)}",
            "# You may edit a copy before applying it.",
        ]
    )


def generated_manifest_paths(config: MatrixConfig) -> set[Path]:
    return {
        path
        for path in config.recipe_root.glob("deploy-*.yaml")
        if (
            GENERATED_MANIFEST_PREFIX in (content := path.read_text(encoding="utf-8"))
            or LEGACY_MATRIX_RENDER_COMMAND_PREFIX in content
            or LEGACY_GENERATED_MANIFEST_PREFIX in content
        )
    }


def is_current_generated_manifest(config: MatrixConfig, path: Path) -> bool:
    marker = f"{GENERATED_MANIFEST_PREFIX}{config.command_path}"
    return marker in path.read_text(encoding="utf-8")


def render_overlay(config: MatrixConfig, overlay_dir: Path) -> str:
    result = subprocess.run(
        [*kustomize_command(), str(overlay_dir)],
        cwd=REPO_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or result.stdout.strip())
    rendered = reorder_rendered_top_level_fields(result.stdout)
    rendered = restore_source_comments(rendered, overlay_dir)
    return f"{SPDX_HEADER}\n\n{rendered_header(config, overlay_dir)}\n\n{rendered}"


def render_matrix(
    config: MatrixConfig, *, check: bool, clean: bool = False
) -> list[Path]:
    stale_overlays = unfold_matrix(config, check=True)
    if stale_overlays:
        if clean and not check:
            unfold_matrix(config, check=False, clean=True)
        else:
            raise RuntimeError(
                f"generated overlays are stale for {config.command_path}; run "
                f"scripts/kustomize-matrix.py unfold {config.command_path}"
            )
    generate_kustomize_openapi(check=check)

    variants = expand_matrix(config)
    expected_outputs = {
        config.recipe_root / f"deploy-{variant.name}.yaml" for variant in variants
    }
    stale: list[Path] = []
    for variant in variants:
        output_path = config.recipe_root / f"deploy-{variant.name}.yaml"
        rendered = render_overlay(config, overlay_path(config, variant))
        current = (
            output_path.read_text(encoding="utf-8") if output_path.exists() else None
        )
        if current != rendered:
            stale.append(output_path)
            if not check:
                output_path.write_text(rendered, encoding="utf-8")

    for output_path in generated_manifest_paths(config) - expected_outputs:
        stale.append(output_path)
        if not check and (clean or is_current_generated_manifest(config, output_path)):
            output_path.unlink()
    return stale


def generated_kustomization(target: Path, components: list[Path], root: Path) -> str:
    lines = [
        "apiVersion: kustomize.config.k8s.io/v1beta1",
        "kind: Kustomization",
        "sortOptions:",
        "  order: fifo",
        "resources:",
        f"  - {json.dumps(relative_path(target, root))}",
    ]
    if components:
        lines.append("components:")
        lines.extend(
            f"  - {json.dumps(relative_path(component, root))}"
            for component in components
        )
    return "\n".join(lines) + "\n"


def compose(target: str, components: list[str], build_options: list[str]) -> int:
    target_path = Path(target).resolve()
    if not target_path.is_dir():
        raise ValueError(f"Kustomize target is not a directory: {target}")
    component_paths = [Path(component).resolve() for component in components]
    missing_components = [
        component for component in component_paths if not component.is_dir()
    ]
    if missing_components:
        raise ValueError(
            f"Kustomize Component is not a directory: {missing_components[0]}"
        )
    common_path = Path(os.path.commonpath([target_path, *component_paths]))
    temporary_parent = target_path.parent if common_path == target_path else common_path
    with tempfile.TemporaryDirectory(
        prefix=".kustomize-matrix-", dir=temporary_parent
    ) as temporary_directory:
        temporary_root = Path(temporary_directory)
        (temporary_root / KUSTOMIZATION_FILE).write_text(
            generated_kustomization(target_path, component_paths, temporary_root),
            encoding="utf-8",
        )
        return subprocess.run(
            [*kustomize_command(), str(temporary_root), *build_options], check=False
        ).returncode


def matrix_paths(paths: list[str]) -> list[str]:
    if paths:
        return paths
    return [
        str(path)
        for path in sorted(REPO_ROOT.glob("recipes/**/.kustomize-matrix.yaml"))
    ]


def report_stale(kind: str, stale_paths: list[Path]) -> int:
    if not stale_paths:
        return 0
    print(f"Generated {kind} are stale:", file=sys.stderr)
    for path in sorted(set(stale_paths)):
        print(f"  {display_path(path)}", file=sys.stderr)
    return 1


def command_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    for command in ("unfold", "render"):
        command_parser = subparsers.add_parser(command)
        mode = command_parser.add_mutually_exclusive_group()
        mode.add_argument("--check", action="store_true")
        mode.add_argument("--clean", action="store_true")
        command_parser.add_argument("matrices", nargs="+")
    check_parser = subparsers.add_parser("check")
    check_parser.add_argument("matrices", nargs="*")
    compose_parser = subparsers.add_parser("compose")
    compose_parser.add_argument("target")
    compose_parser.add_argument("arguments", nargs=argparse.REMAINDER)
    return parser


def main(arguments: list[str] | None = None) -> int:
    args = command_parser().parse_args(arguments)
    try:
        if args.command == "compose":
            component_end = 0
            while component_end < len(args.arguments) and not args.arguments[
                component_end
            ].startswith("-"):
                component_end += 1
            return compose(
                args.target,
                args.arguments[:component_end],
                args.arguments[component_end:],
            )

        configs = [load_matrix(path) for path in matrix_paths(args.matrices)]
        if not configs:
            raise ValueError("no .kustomize-matrix.yaml files found")
        if args.command == "unfold":
            stale_overlays = [
                path
                for config in configs
                for path in unfold_matrix(config, check=args.check, clean=args.clean)
            ]
            return (
                report_stale("Kustomize overlays", stale_overlays) if args.check else 0
            )
        if args.command == "render":
            stale_manifests = [
                path
                for config in configs
                for path in render_matrix(config, check=args.check, clean=args.clean)
            ]
            return (
                report_stale("recipe manifests", stale_manifests) if args.check else 0
            )

        stale_overlays = [
            path for config in configs for path in unfold_matrix(config, check=True)
        ]
        stale_manifests = (
            []
            if stale_overlays
            else [
                path for config in configs for path in render_matrix(config, check=True)
            ]
        )
        return report_stale("Kustomize overlays", stale_overlays) or report_stale(
            "recipe manifests", stale_manifests
        )
    except (OSError, RuntimeError, TypeError, ValueError) as exc:
        print(f"kustomize-matrix: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
