# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Deterministic serialization for the Dynamo Python API docs.

Consumes the discovered :class:`~api_discovery.Module` /
:class:`~api_discovery.Symbol` / :class:`~api_discovery.Method` values and
turns them into two generator outputs, both built from Fern's own components:

* one MDX page per curated module -- an anchored ``<Accordion>`` per symbol,
  with the import statement and signature in Python code fences; and
* the Python API landing page, a ``<CardGroup>`` indexing every module.

No I/O happens here -- callers are responsible for writing the returned
text. Deterministic in, deterministic out: identical inputs must produce
byte-identical outputs so ``--check`` and diff review stay reliable.
"""

from __future__ import annotations

import re
from collections.abc import Iterable

from api_discovery import DocSection, DocTerm, Method, Module, Symbol
from markdown_rendering import escape_mdx_prose, mdx_attribute

MDX_GENERATED_MARKER = (
    "{/* GENERATED by docs/fern/scripts/gen_python_api.py -- do not edit. */}"
)

# Bold lead-ins rather than headings: an Accordion body sits inside the page's
# heading outline, so a real heading here would pollute the right-hand nav.
_SECTION_HEADINGS: dict[str, str] = {
    "parameters": "**Parameters**",
    "attributes": "**Attributes**",
    "returns": "**Returns**",
    "yields": "**Yields**",
    "raises": "**Raises**",
    "examples": "**Examples**",
}

# Fern ships these callouts natively; anything else degrades to a plain Note
# rather than emitting a component the site does not define.
_ADMONITION_TAGS: dict[str, str] = {
    "note": "Note",
    "info": "Info",
    "tip": "Tip",
    "hint": "Tip",
    "warning": "Warning",
    "caution": "Warning",
    "danger": "Warning",
    "important": "Warning",
}


# ---------------------------------------------------------------------------
# MDX rendering (whole-file writes)
# ---------------------------------------------------------------------------


def symbol_anchor(symbol: Symbol) -> str:
    """Stable, page-unique DOM id for one symbol's deep link."""
    slug = re.sub(r"[^a-z0-9]+", "-", symbol.qualname.lower()).strip("-")
    return f"api-{slug}"


def method_anchor(symbol: Symbol, method: Method) -> str:
    """Stable, page-unique DOM id for one method's deep link.

    Qualifying by the owning symbol is what makes this page-unique: method
    names repeat across classes on a module page (``initialize`` sits on both
    ``Connection`` and ``Connector``), so a bare heading id would collide and
    Fern would resolve the link to whichever came first.
    """
    slug = re.sub(r"[^a-z0-9]+", "-", method.name.lower()).strip("-")
    return f"{symbol_anchor(symbol)}-{slug}"


def import_statement(symbol: Symbol) -> str:
    """Valid Python import statement, preserving a public alias name."""
    module_name, import_name = symbol.import_path.rsplit(".", 1)
    return f"from {module_name} import {import_name}"


def render_module_page(module: Module) -> str:
    """Full MDX text for one per-module page."""
    parts = [_module_frontmatter(module).rstrip("\n"), "", MDX_GENERATED_MARKER, ""]
    parts.append(_module_intro(module))
    for symbol in module.symbols:
        parts.append("")
        parts.append("\n".join(_symbol_section(symbol)))
    return "\n".join(parts).rstrip() + "\n"


def _module_frontmatter(module: Module) -> str:
    """SPDX header plus title/subtitle for one module page."""
    return (
        "---\n"
        "# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION "
        "& AFFILIATES. All rights reserved.\n"
        "# SPDX-License-Identifier: Apache-2.0\n"
        f"title: {module.name}\n"
        f"subtitle: {_escape_yaml(module.summary)}\n"
        "---\n"
    )


def _module_intro(module: Module) -> str:
    """Symbol counts and a source link above the per-symbol accordions."""
    classes = sum(1 for s in module.symbols if s.kind == "class")
    functions = sum(1 for s in module.symbols if s.kind == "function")
    return (
        f"`{module.name}` publishes {classes} classes and {functions} functions. "
        f"Source: [`{module.source_path}`]({module.source_href})"
    )


def _symbol_section(symbol: Symbol) -> list[str]:
    """One anchored accordion carrying a symbol's signature and methods.

    The explicit id keeps deep links stable: Fern's own title-derived id
    collides for same-named symbols across submodules.
    """
    title = mdx_attribute(f"{symbol.name} ({symbol.kind})")
    return [
        f'<Accordion id="{symbol_anchor(symbol)}" title="{title}">',
        *_symbol_body(symbol),
        "</Accordion>",
    ]


def _symbol_body(symbol: Symbol) -> list[str]:
    """Lead, import fence, signature, docstring detail, source, methods."""
    lead, detail = _split_lead(symbol)
    lines = [lead, ""]
    lines += ["```python", import_statement(symbol), "```"]
    if symbol.signature:
        lines += ["", "```python", symbol.signature, "```"]
    lines += _docstring_detail(detail)
    lines += [
        "",
        f"[`{symbol.source_path}#L{symbol.source_line}`]({symbol.source_href})",
    ]
    if symbol.methods:
        lines += ["", "**Public methods**"]
        for method in symbol.methods:
            lines += ["", *_method_block(symbol, method)]
    return lines


def _split_lead(documented: Symbol | Method) -> tuple[str, tuple[DocSection, ...]]:
    """The opening line of a documented entry, and the sections after it.

    Takes a symbol or a method because both carry the same ``summary`` and
    ``docs`` pair, and both need the first paragraph split off the rest.

    :attr:`Symbol.summary` stops at the docstring's first newline because the
    index cards and page subtitles need one short line. Leading with that
    here would strand a wrapped opening sentence mid-clause, so the accordion
    leads with the whole first paragraph and the remaining prose moves below
    the signature.
    """
    sections = documented.docs
    if not sections or sections[0].kind != "text":
        return escape_mdx_prose(documented.summary) or "No summary available.", sections
    head, _, tail = sections[0].text.partition("\n\n")
    lead = escape_mdx_prose(" ".join(head.split()))
    rest = list(sections[1:])
    if tail.strip():
        rest.insert(0, DocSection(kind="text", text=tail.strip()))
    return lead or "No summary available.", tuple(rest)


def _docstring_detail(sections: Iterable[DocSection]) -> list[str]:
    """Every docstring section below the summary, in authored order.

    Order is preserved rather than regrouped so the rendered page reads the
    way the docstring was written.
    """
    lines: list[str] = []
    for section in sections:
        rendered = _render_section(section)
        if rendered:
            lines += ["", *rendered]
    return lines


def _render_section(section: DocSection) -> list[str]:
    """Dispatch one section onto its native MDX form."""
    if section.kind == "text":
        return _prose_block(section.text)
    if section.kind == "admonition":
        return _admonition(section)
    heading = _SECTION_HEADINGS.get(section.kind)
    if heading is None:
        return []
    if section.kind == "examples":
        return [heading, "", *_example_blocks(section)]
    if section.kind in ("parameters", "attributes"):
        return [heading, "", *_param_fields(section.terms)]
    return [heading, "", *(_term_bullet(term) for term in section.terms)]


def _prose_block(text: str) -> list[str]:
    """Escape multi-line prose one line at a time.

    Escaping the block as a single string would let an unbalanced backtick
    pair across a blank line and swallow a whole paragraph into a false code
    span, so each line is escaped independently.

    reST literal blocks introduced by ``::`` are lifted into Markdown code
    fences before per-line escaping so the indented example body renders as
    a code block rather than getting flattened into ordinary prose.
    """
    normalized = _normalize_rest_literal_blocks(text)
    output: list[str] = []
    in_fence = False
    for line in normalized.splitlines():
        stripped = line.strip()
        if stripped.startswith("```"):
            output.append(line)
            in_fence = not in_fence
            continue
        if in_fence:
            output.append(line)
            continue
        output.append(escape_mdx_prose(line) if stripped else "")
    return output


def _normalize_rest_literal_blocks(text: str) -> str:
    """Convert reST ``::`` literal blocks into Markdown code fences.

    A trailing ``::`` (either standalone or attached to the preceding word)
    introduces an indented literal block after a blank line. The block ends
    when a line dedents to at or below the paragraph indentation, matching
    docutils. Standalone ``::`` is dropped entirely; an attached form drops
    only the trailing double colon so the sentence keeps a single ``:``.
    """
    lines = text.splitlines()
    result: list[str] = []
    index = 0
    while index < len(lines):
        line = lines[index]
        if not _introduces_literal_block(line):
            result.append(line)
            index += 1
            continue
        marker_indent = len(line) - len(line.lstrip(" "))
        stripped = line.rstrip()
        if stripped == "::":
            head = None
        else:
            head = stripped[:-2].rstrip()
            if head.endswith(":"):
                head = head[:-1]
        blank_index = index + 1
        while blank_index < len(lines) and not lines[blank_index].strip():
            blank_index += 1
        block_start = blank_index
        block_end = block_start
        block_indent: int | None = None
        while block_end < len(lines):
            candidate = lines[block_end]
            if not candidate.strip():
                block_end += 1
                continue
            indent = len(candidate) - len(candidate.lstrip(" "))
            if indent <= marker_indent:
                break
            if block_indent is None:
                block_indent = indent
            block_end += 1
        if block_indent is None:
            result.append(line)
            index += 1
            continue
        if head is not None:
            result.append(" " * marker_indent + head)
        result.append("")
        result.append("```")
        for body_line in lines[block_start:block_end]:
            if body_line.strip():
                result.append(body_line[block_indent:])
            else:
                result.append("")
        result.append("```")
        index = block_end
    return "\n".join(result)


def _introduces_literal_block(line: str) -> bool:
    """True when ``line`` ends in ``::`` (reST literal-block introducer)."""
    stripped = line.rstrip()
    if not stripped.endswith("::"):
        return False
    if stripped == "::":
        return True
    return len(stripped) >= 3 and stripped[-3] != ":"


def _param_fields(terms: Iterable[DocTerm]) -> list[str]:
    """One ``<ParamField>`` per documented entry.

    The same native component the Kubernetes API page uses for CRD schema
    fields, so both references present a parameter identically.
    """
    lines: list[str] = []
    for term in terms:
        attrs = [f'path="{mdx_attribute(term.name)}"']
        if term.annotation:
            attrs.append(f'type="{mdx_attribute(term.annotation)}"')
        lines.append(f"<ParamField {' '.join(attrs)}>")
        lines += _prose_block(term.description)
        lines.append("</ParamField>")
    return lines


def _term_bullet(term: DocTerm) -> str:
    """One returns/raises entry as a labelled bullet.

    These are not parameters -- a raise has no path and a return has no name
    to bind -- so they read better as a list than as a ``<ParamField>``.
    """
    label = term.annotation or term.name
    description = escape_mdx_prose(" ".join(term.description.split()))
    if label and description:
        return f"- `{label}` — {description}"
    return f"- `{label}`" if label else f"- {description}"


def _example_blocks(section: DocSection) -> list[str]:
    """Code samples as Python fences, interleaved prose as prose."""
    lines: list[str] = []
    for index, (kind, text) in enumerate(section.blocks):
        if index:
            lines.append("")
        if kind == "text":
            lines += _prose_block(text)
        else:
            lines += ["```python", text, "```"]
    return lines


def _admonition(section: DocSection) -> list[str]:
    """One griffe admonition as a native Fern callout."""
    tag = _ADMONITION_TAGS.get(section.label, "Note")
    return [f"<{tag}>", *_prose_block(section.text), f"</{tag}>"]


def _method_block(symbol: Symbol, method: Method) -> list[str]:
    """One public method as an anchored heading, signature, and its sections.

    Every method renders through this one shape whether or not its docstring
    documents parameters. Promoting only the documented ones would let
    docstring coverage decide the page's visual rhythm, so a class whose
    trivial method happens to carry ``Args:`` would give that method more
    prominence than the load-bearing one beside it.

    The heading is raw ``<h4>`` rather than Markdown because the id has to be
    qualified by the owning class to stay unique, and Fern derives Markdown
    heading ids from the text alone. It carries its name as visible text, so
    it is not the empty ``<a id>`` this generator replaced.
    """
    lead, detail = _split_lead(method)
    anchor = method_anchor(symbol, method)
    return [
        f'<h4 id="{anchor}">{escape_mdx_prose(method.name)}</h4>',
        "",
        "```python",
        method.signature,
        "```",
        "",
        lead,
        *_docstring_detail(detail),
        "",
        f"[source]({method.source_href})",
    ]


def render_landing_page(modules: Iterable[Module]) -> str:
    """Full MDX text for the Python API landing page."""
    module_list = list(modules)
    frontmatter = (
        "---\n"
        "# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION "
        "& AFFILIATES. All rights reserved.\n"
        "# SPDX-License-Identifier: Apache-2.0\n"
        "title: Python API\n"
        "subtitle: Public Python surfaces on the Dynamo distributed runtime, "
        "statically discovered from the source tree.\n"
        "---\n"
    )
    parts = [frontmatter.rstrip("\n"), "", MDX_GENERATED_MARKER, ""]
    parts.append(_landing_body(module_list))
    return "\n".join(parts).rstrip() + "\n"


def _landing_body(modules: list[Module]) -> str:
    """Lead paragraph plus one navigation card per discovered module."""
    total = sum(len(m.symbols) for m in modules)
    lines = [
        f"Dynamo publishes {len(modules)} Python modules with {total} public "
        "class and function symbols under `dynamo.*`.",
        "",
        "<CardGroup cols={2}>",
    ]
    for module in modules:
        lines.append(
            f'<Card title="{mdx_attribute(module.name)}" '
            f'href="python/{module.slug}">'
            f"{len(module.symbols)} symbols. "
            f"{escape_mdx_prose(module.summary)}</Card>"
        )
    lines.append("</CardGroup>")
    return "\n".join(lines)


def _escape_yaml(text: str) -> str:
    """Minimal YAML-safe scalar for the subtitle field."""
    return text.replace('"', '\\"')
