#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate agent-facing twins of the Reference-page component data.

Three Reference pages (pages/reference/general/compatibility.mdx,
reference/general/release-artifacts.mdx, reference/general/model-early-access-builds.mdx)
render their data through custom React components, whose output may be absent
from Fern's agent-facing markdown exports (.md endpoints, llms.txt). This
script reads the single source of truth ``components/releases.data.ts`` and
emits equivalent markdown tables into each page between idempotent markers,
wrapped in <llms-only> so only agent exports see them.

reference/compatibility.mdx's human-facing release support matrix is a
React component (``ReleaseSupportMatrix``, in ``components/``); its data
comes from the same ``releases.data.ts`` module this script parses, so the
human and agent views cannot drift. This script therefore only emits the
``llms-tables`` twin for that page — a single flat CUDA / feature / pins
table optimized for parsing.

reference/release-notes/README.mdx (Release History) carries a second
human-facing span, ``release-stats``: the per-release PR, contributor,
breaking-change, and known-issue counts. Those counts otherwise appeared
only in releases-data.mdx, which is hidden from the sidebar, so on the page
they had no reader-visible home at all. Both spans render from
``release_stats_table`` so the visible table and the agent mirror cannot
diverge. Like ``support-matrix`` it fails closed when its markers are
missing, keeping placement under human control.

It also emits three machine-readable outputs from the same parse:

  * pages/reference/general/releases-machine-readable.mdx — a "Releases (machine-readable)" page whose
    body (between the same idempotent markers, NOT <llms-only>-wrapped) is the
    full releases.data.ts content as plain markdown tables.
  * assets/releases.json — a stable-schema JSON serialization of the parsed
    data (current, mainTot, releases, cudaHistory, features, artifacts,
    modelEaBuilds, platform, releaseStats, ...). Human dates gain ISO-8601
    ``dateIso`` twins.
  * assets/releases-atom.xml — an Atom 1.0 feed, one entry per RELEASES item,
    newest first. Entry links resolve notesHref against the canonical prod
    base (https://docs.nvidia.com/dynamo), falling back to the GitHub release
    URL. The feed ``updated`` stamp is the newest release date (deterministic
    — never "now").

Usage (from any cwd; paths resolve relative to this file):

    python3 gen_llms_tables.py               # write/refresh all outputs
    python3 gen_llms_tables.py --check       # check marker-spliced pages, no writes
    python3 gen_llms_tables.py --assets-only # write/refresh only JSON and Atom

Re-run at every release bump, after editing releases.data.ts.

The parser is deliberately conservative: releases.data.ts must stay a
disciplined literal (see PARSER CONTRACT below). Any construct the parser
does not understand aborts the run with a clear error -- partial output is
never emitted.

PARSER CONTRACT (keep releases.data.ts within these bounds):
  * Top-level declarations of the form ``[export] const NAME[: Type] = <literal>;``
  * Literal values: object/array literals, string literals ('...' or "..."),
    template literals whose only interpolations are ``${IDENT}`` where IDENT
    is a previously declared string const (e.g. ``${GH}``, ``${NGC_C}``),
    numbers, true/false/null, and bare identifier references to previously
    declared consts (e.g. ``coverage: MODEL_COVERAGE``).
  * Object keys: bare identifiers or quoted strings.
  * No computed values, spreads, function calls, arithmetic, or ternaries.
"""

from __future__ import annotations

import argparse
import copy
import json
import re
import sys
from pathlib import Path
from typing import Callable, NamedTuple

SCRIPT_DIR = Path(__file__).resolve().parent
DATA_TS = SCRIPT_DIR.parent / "components" / "releases.data.ts"
REFERENCE_DIR = SCRIPT_DIR.parent / "pages" / "reference" / "general"
ASSETS_DIR = SCRIPT_DIR.parent / "assets"
JSON_PATH = ASSETS_DIR / "releases.json"
ATOM_PATH = ASSETS_DIR / "releases-atom.xml"

# Canonical prod host; notesHref values are absolute site paths (/dynamo/...).
PROD_HOST = "https://docs.nvidia.com"
PROD_BASE = f"{PROD_HOST}/dynamo"

GENERATOR_NOTE = "generated by scripts/gen_llms_tables.py, do not edit"


def marker_begin(marker: str) -> str:
    return f"{{/* {marker}:begin — {GENERATOR_NOTE} */}}"


def marker_end(marker: str) -> str:
    return f"{{/* {marker}:end */}}"


# Exports the generator depends on. Parsing aborts if any is missing.
REQUIRED_EXPORTS = [
    "RELEASES",
    "MAIN_TOT",
    "CURRENT_VERSION",
    "CURRENT_DATE",
    "CURRENT_TAG",
    "CURRENT_WHEEL",
    "CUDA_HISTORY",
    "FEATURES",
    "FEATURE_INTERACTIONS",
    "ARTIFACTS",
    "MODEL_EA_BUILDS",
    "PLATFORM",
    "PLATFORM_PREVIEW_COVERAGE",
    "KNOWN_ARTIFACT_ISSUES",
    "CRATES_FIRST_PUBLISHED",
    "RELEASE_STATS",
]


class TSParseError(Exception):
    """releases.data.ts contains a construct the conservative parser rejects."""


# ---------------------------------------------------------------------------
# TypeScript literal parsing (stdlib only, no TS runtime)
# ---------------------------------------------------------------------------


def strip_comments(src: str) -> str:
    """Remove // and /* */ comments, preserving string/template contents.

    A character walk (not regex) so that ``https://...`` inside strings and
    comment-like sequences inside template literals survive intact.
    """
    out: list[str] = []
    i, n = 0, len(src)
    while i < n:
        c = src[i]
        if c in "\"'`":
            quote = c
            out.append(c)
            i += 1
            while i < n:
                ch = src[i]
                out.append(ch)
                if ch == "\\" and i + 1 < n:  # keep escaped char verbatim
                    out.append(src[i + 1])
                    i += 2
                    continue
                i += 1
                if ch == quote:
                    break
            continue
        if c == "/" and i + 1 < n and src[i + 1] == "/":
            while i < n and src[i] != "\n":
                i += 1
            continue
        if c == "/" and i + 1 < n and src[i + 1] == "*":
            end = src.find("*/", i + 2)
            if end == -1:
                raise TSParseError("unterminated /* */ comment")
            # Preserve newlines so any future error positions stay meaningful.
            out.append("\n" * src.count("\n", i, end))
            i = end + 2
            continue
        out.append(c)
        i += 1
    return "".join(out)


class LiteralParser:
    """Recursive-descent parser for disciplined TS object/array literals."""

    def __init__(self, src: str, env: dict):
        self.src = src
        self.i = 0
        self.env = env  # previously parsed consts, for ${IDENT} / bare refs

    def error(self, msg: str) -> TSParseError:
        line = self.src.count("\n", 0, self.i) + 1
        context = self.src[self.i : self.i + 40].replace("\n", "\\n")
        return TSParseError(f"{msg} (near line {line}: {context!r})")

    def ws(self) -> None:
        while self.i < len(self.src) and self.src[self.i] in " \t\r\n":
            self.i += 1

    def peek(self) -> str:
        return self.src[self.i] if self.i < len(self.src) else ""

    def expect(self, ch: str) -> None:
        if self.peek() != ch:
            raise self.error(f"expected {ch!r}")
        self.i += 1

    def parse_value(self):
        self.ws()
        c = self.peek()
        if c == "{":
            return self.parse_object()
        if c == "[":
            return self.parse_array()
        if c in "\"'":
            return self.parse_string(c)
        if c == "`":
            return self.parse_template()
        if c.isdigit() or c == "-":
            return self.parse_number()
        if c.isalpha() or c == "_":
            return self.parse_word()
        raise self.error("unexpected token")

    def parse_object(self) -> dict:
        self.expect("{")
        obj: dict = {}
        while True:
            self.ws()
            if self.peek() == "}":
                self.i += 1
                return obj
            key = self.parse_key()
            self.ws()
            self.expect(":")
            obj[key] = self.parse_value()
            self.ws()
            if self.peek() == ",":
                self.i += 1
            elif self.peek() != "}":
                raise self.error("expected ',' or '}' in object")

    def parse_key(self) -> str:
        c = self.peek()
        if c in "\"'":
            return self.parse_string(c)
        m = re.match(r"[A-Za-z_$][\w$]*", self.src[self.i :])
        if not m:
            raise self.error("expected object key")
        self.i += m.end()
        return m.group(0)

    def parse_array(self) -> list:
        self.expect("[")
        arr: list = []
        while True:
            self.ws()
            if self.peek() == "]":
                self.i += 1
                return arr
            arr.append(self.parse_value())
            self.ws()
            if self.peek() == ",":
                self.i += 1
            elif self.peek() != "]":
                raise self.error("expected ',' or ']' in array")

    def parse_string(self, quote: str) -> str:
        self.expect(quote)
        out: list[str] = []
        while True:
            if self.i >= len(self.src):
                raise self.error("unterminated string")
            c = self.src[self.i]
            if c == "\\":
                out.append(self.unescape())
                continue
            self.i += 1
            if c == quote:
                return "".join(out)
            out.append(c)

    def parse_template(self) -> str:
        """Template literal; only ``${IDENT}`` interpolations of known
        string consts are allowed (the ``${GH}`` / ``${NGC_C}`` prefixes)."""
        self.expect("`")
        out: list[str] = []
        while True:
            if self.i >= len(self.src):
                raise self.error("unterminated template literal")
            c = self.src[self.i]
            if c == "\\":
                out.append(self.unescape())
                continue
            if c == "`":
                self.i += 1
                return "".join(out)
            if c == "$" and self.src[self.i : self.i + 2] == "${":
                m = re.match(r"\$\{([A-Za-z_$][\w$]*)\}", self.src[self.i :])
                if not m:
                    raise self.error("only ${IDENT} interpolation is supported")
                name = m.group(1)
                if name not in self.env or not isinstance(self.env[name], str):
                    raise self.error(
                        f"${{{name}}}: not a previously declared string const"
                    )
                out.append(self.env[name])
                self.i += m.end()
                continue
            out.append(c)
            self.i += 1

    def unescape(self) -> str:
        esc = self.src[self.i + 1] if self.i + 1 < len(self.src) else ""
        self.i += 2
        return {"n": "\n", "t": "\t", "r": "\r"}.get(esc, esc)

    def parse_number(self):
        m = re.match(r"-?\d+(?:\.\d+)?", self.src[self.i :])
        if not m:
            raise self.error("bad number")
        self.i += m.end()
        text = m.group(0)
        return float(text) if "." in text else int(text)

    def parse_word(self):
        m = re.match(r"[A-Za-z_$][\w$]*", self.src[self.i :])
        word = m.group(0)
        self.i += m.end()
        if word == "true":
            return True
        if word == "false":
            return False
        if word in ("null", "undefined"):
            return None
        # Bare identifier reference to a previously declared const
        # (e.g. ``coverage: MODEL_COVERAGE``). Deep-copied so shared
        # references never alias each other in the parsed data.
        if word in self.env:
            return copy.deepcopy(self.env[word])
        raise self.error(f"unknown identifier {word!r}")


DECL_RE = re.compile(
    r"^\s*(?:export\s+)?const\s+([A-Za-z_$][\w$]*)\s*(?::[^=;]+?)?=",
    re.MULTILINE,
)


def parse_data_module(path: Path) -> dict:
    """Parse every top-level const in releases.data.ts into a dict."""
    try:
        src = strip_comments(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise TSParseError(f"cannot read {path}: {exc}") from exc

    env: dict = {}
    for m in DECL_RE.finditer(src):
        name = m.group(1)
        parser = LiteralParser(src, env)
        parser.i = m.end()
        try:
            env[name] = parser.parse_value()
        except TSParseError as exc:
            raise TSParseError(f"while parsing const {name}: {exc}") from exc
        parser.ws()
        if parser.peek() == ";":
            parser.i += 1

    missing = [n for n in REQUIRED_EXPORTS if n not in env]
    if missing:
        raise TSParseError(f"missing required exports: {', '.join(missing)}")
    return env


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------


def cell(value) -> str:
    """Sanitize a value for a markdown table cell."""
    if value is None or value == "":
        return "-"
    return str(value).replace("|", "\\|").replace("\n", " ")


def md_table(headers: list[str], rows: list[list]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell(v) for v in row) + " |")
    return "\n".join(lines)


def nixl_cell(pins: dict) -> str:
    parts = [pins.get(k) or "-" for k in ("nixlSglang", "nixlTrtllm", "nixlVllm")]
    return " / ".join(parts) if any(p != "-" for p in parts) else "-"


FEATURE_STATUS_LABEL = {
    "yes": "Supported",
    "caveat": "Supported with caveat",
    "wip": "Experimental",
    "no": "Not supported",
}


def feature_cell(fc: dict) -> str:
    status = fc.get("status")
    if status not in FEATURE_STATUS_LABEL:
        raise TSParseError(f"unknown feature status {status!r}")
    label = FEATURE_STATUS_LABEL[status]
    note = fc.get("note")
    return f"{label} ({note})" if note else label


# ---------------------------------------------------------------------------
# Shared section renderers (composed by both the per-page <llms-only> twins
# and the machine-readable releases-machine-readable.mdx page; each returns a headerless
# fragment so every call site can supply its own heading style).
# ---------------------------------------------------------------------------


def cuda_table(data: dict, versions: set[str] | None = None) -> str:
    """CUDA toolkit and minimum-driver history table.

    ``versions`` optionally restricts the rows to a set of bare release
    versions (e.g. ``{"1.3.0", "1.2.0"}``); ``None`` emits the full history.
    """
    rows = [
        [r["version"], r["backend"], r["toolkit"], r["minDriver"], r.get("note")]
        for r in data["CUDA_HISTORY"]
        if versions is None or r["version"] in versions
    ]
    return md_table(["Dynamo", "Backend", "CUDA Toolkit", "Min Driver", "Note"], rows)


def feature_table(data: dict) -> str:
    """Feature-support-by-backend table."""
    rows = [
        [
            f["name"],
            feature_cell(f["sglang"]),
            feature_cell(f["trtllm"]),
            feature_cell(f["vllm"]),
        ]
        for f in data["FEATURES"]
    ]
    return md_table(["Feature", "SGLang", "TensorRT-LLM", "vLLM"], rows)


INTERACTION_GLYPH = {"yes": "Yes", "wip": "Experimental", "no": "No", "na": "n/a"}


def interaction_tables(data: dict) -> str:
    """Pairwise feature-interaction matrices, one table per backend.

    The human view renders through <FeatureInteractions />, whose cell states
    live in the DOM as tinted divs with no text; Fern's agent-facing export
    would carry no status at all. This twin restates every cell as words from
    the same FEATURE_INTERACTIONS data, so the two cannot disagree.

    Only the lower triangle is stored, so the upper triangle is filled in here
    by mirroring -- an agent reading a row should not have to know the
    convention to answer "does A work with B".
    """
    parts: list[str] = []
    for matrix in data["FEATURE_INTERACTIONS"]:
        features = matrix["features"]
        rows_in = matrix["rows"]
        grid: list[list] = [[None] * len(features) for _ in features]
        for r, cells in enumerate(rows_in):
            for c, cell in enumerate(cells):
                grid[r][c] = cell
                if r != c:
                    grid[c][r] = cell  # mirror, so both directions read alike
        body: list[list] = []
        for r, feature in enumerate(features):
            row = [feature]
            for c in range(len(features)):
                cell = grid[r][c]
                if cell is None:
                    row.append(None)
                    continue
                # Raised as TSParseError like every other parse failure in
                # this module: a bare KeyError is caught by main() and shown
                # as "KeyError('preview')", which names neither the map nor
                # the fix. Matches feature_cell above.
                status = cell["status"]
                if status not in INTERACTION_GLYPH:
                    raise TSParseError(
                        f"unknown interaction status {status!r} for "
                        f"{matrix['backend']}; add it to INTERACTION_GLYPH"
                    )
                text = INTERACTION_GLYPH[status]
                note = cell.get("note")
                if note:
                    source = cell.get("source")
                    suffix = f" ({PROD_HOST}{source})" if source else ""
                    text = f"{text} — {note}{suffix}"
                row.append(text)
            body.append(row)
        parts.append(f"*{matrix['backend']}*")
        parts.append(md_table(["Feature", *features], body))
    return "\n\n".join(parts)


def artifact_table(data: dict) -> str:
    """Artifact-inventory table."""
    rows: list[list] = []
    for art in data["ARTIFACTS"]:
        name = art["name"]
        if art.get("badge"):
            name = f"{name} ({art['badge']})"
        tags = "; ".join(f"`{t['clipboard']}`" for t in art.get("tags", []))
        rows.append([art["category"], name, art["description"], art.get("meta"), tags])
    return md_table(["Category", "Name", "Description", "Meta", "Tags / install"], rows)


def nightlies_table(data: dict) -> str:
    """Recent pinned nightly wheel builds."""
    rows = [
        [b["version"], b["date"], ", ".join(b["packages"]), b.get("note")]
        for b in data.get("NIGHTLY_BUILDS", [])
    ]
    return md_table(["Version", "Date", "Packages", "Notes"], rows)


def known_issues_table(data: dict) -> str:
    """Known-artifact-issues table."""
    rows = [
        [i["version"], i["artifact"], i["issue"], i["status"]]
        for i in data["KNOWN_ARTIFACT_ISSUES"]
    ]
    return md_table(["Release", "Artifact", "Issue", "Status"], rows)


def crates_table(data: dict) -> str:
    """First-published-version-on-crates.io table."""
    rows = [
        [c["crate"], c["version"], c["date"]] for c in data["CRATES_FIRST_PUBLISHED"]
    ]
    return md_table(["Crate", "First version", "Date"], rows)


def platform_lines(data: dict) -> str:
    """Platform-support bullet lines (GPUs / OS / CPU arch / wheels).

    OS rows carry a ``scope`` field distinguishing shipped container bases
    ("Containers and wheels") from wheels-only hosts ("Wheels only"); csp rows
    carry the same field — see
    releases.data.ts for the reasoning.
    """
    plat = data["PLATFORM"]
    lines = [f"- GPU architectures: {', '.join(plat['gpus'])}"]
    for os_row in plat["os"]:
        lines.append(
            f"- OS: {os_row['name']} {os_row['version']} ({os_row['arch']}) — {os_row['scope']}"
        )
    for csp in plat.get("csp", []):
        lines.append(
            f"- CSP: {csp['provider']} — {csp['os']} ({csp['arch']}) — {csp['scope']}"
        )
    lines.append(f"- CPU architectures: {', '.join(plat['arch'])}")
    if plat.get("wheelsNote"):
        lines.append(f"- Wheels: {plat['wheelsNote']}")
    return "\n".join(lines)


def ea_table(data: dict) -> str:
    """Model early-access builds table."""
    rows: list[list] = []
    for b in data["MODEL_EA_BUILDS"]:
        cov = b["coverage"]
        cov_cell = " / ".join(
            "yes" if cov.get(k) else "no"
            for k in ("images", "wheels", "helm", "crates")
        )
        rows.append(
            [
                b["model"],
                f"`{b['tag']}`",
                b["releaseLine"],
                ", ".join(b["runtimes"]),
                b["shipped"],
                b["gaLabel"],
                b["statusLine"],
                cov_cell,
            ]
        )
    return md_table(
        [
            "Model",
            "Tag",
            "Release line",
            "Runtimes",
            "Shipped",
            "GA path",
            "Status",
            "Coverage (images / wheels / helm / crates)",
        ],
        rows,
    )


def render_compatibility(data: dict) -> str:
    parts: list[str] = []
    parts.append(
        f"Current stable release: {data['CURRENT_VERSION']} "
        f"(container tag `{data['CURRENT_TAG']}`, wheel version `{data['CURRENT_WHEEL']}`)."
    )

    # Backend pins: main (ToT) first, then every tracked release, newest first.
    pin_rows: list[list] = []
    tot = data["MAIN_TOT"]
    pin_rows.append(
        [
            "main (ToT)",
            "development head",
            tot.get("sglang"),
            tot.get("trtllm"),
            tot.get("vllm"),
            nixl_cell(tot),
            None,
        ]
    )
    for rel in data["RELEASES"]:
        pins = rel.get("pins") or {}
        pin_rows.append(
            [
                rel["version"],
                rel.get("kind"),
                pins.get("sglang"),
                pins.get("trtllm"),
                pins.get("vllm"),
                nixl_cell(pins),
                rel.get("ucx"),
            ]
        )
    parts.append("**Backend engine pins per Dynamo release**")
    parts.append(
        md_table(
            [
                "Dynamo",
                "Type",
                "SGLang",
                "TensorRT-LLM",
                "vLLM",
                "NIXL (SGL / TRT / vLLM)",
                "UCX",
            ],
            pin_rows,
        )
    )

    # The human view of the CUDA history renders through the
    # <ReleaseSupportMatrix /> React component (which reads the same
    # releases.data.ts module) and Fern's agent-facing .md export may drop
    # component output; this flat twin exists so the matrix survives an
    # agent export whether or not the component's DOM is captured.
    parts.append("**CUDA toolkit and minimum driver per Dynamo release**")
    parts.append(cuda_table(data))
    cuda_notes = data.get("CUDA_NOTES") or []
    if cuda_notes:
        parts.append("\n".join(f"- {note}" for note in cuda_notes))

    parts.append(f"**Feature support by backend ({data['CURRENT_VERSION']})**")
    parts.append(feature_table(data))

    parts.append("**Feature interactions by backend**")
    parts.append(
        "Each cell states whether the row feature works together with the "
        "column feature. The matrix is symmetric: a cell reads the same in "
        "either direction."
    )
    parts.append(interaction_tables(data))

    # Platform support (GPUs / OS / arch) — rendered by CompatibilityHero.
    parts.append("**Platform support**")
    parts.append(platform_lines(data))

    return "\n\n".join(parts)


# Release kinds the human-facing support matrix covers: the lines a reader
# can actually pull and run. Platform previews (-dev.N) and model-specific
# builds are deliberately excluded -- CUDA_NOTES documents the toolkit support
# of those that have it, which is not all of them: v1.3.0-dev.1 and
# v1.2.0-deepseek-v4-dev.2 have no note and no CUDA_HISTORY row, and no CUDA
# version is recorded for them anywhere in the repo. The accordion caption is
# therefore worded to promise coverage only for the builds a note names,
# rather than to send readers of the others after information that is not
# there. CUDA_HISTORY happens to carry no preview or model-build rows
# today, so this filter is currently a no-op; it is expressed on kind anyway
# so a future preview entry cannot leak into the matrix unnoticed.
SUPPORT_MATRIX_KINDS = ("stable", "patch")


def released_versions(data: dict) -> set[str]:
    """Bare versions of the released lines -- stable releases and patches."""
    return {
        rel["version"].removeprefix("v")
        for rel in data["RELEASES"]
        if rel.get("kind") in SUPPORT_MATRIX_KINDS
    }


def parse_driver_floor(min_driver: str) -> int:
    """'580.xx+' -> 580.

    Numeric on purpose. These are compared, and comparing them as strings is
    only accidentally right while every floor has the same digit count -- the
    bug the retired RunsWhereWizard shipped with.
    """
    match = re.match(r"\s*(\d+)", min_driver)
    if not match:
        raise TSParseError(
            f"minDriver {min_driver!r} does not start with a number -- the "
            "driver-floor table cannot place it"
        )
    return int(match.group(1))


def post_train_base(version: str) -> str:
    """'0.7.0.post1' -> '0.7.0'; every other version is returned unchanged.

    Post trains republish images or wheels off an existing release and carry
    no CUDA_HISTORY row of their own -- CUDA_NOTES states they have the same
    CUDA support as their base version.
    """
    return version.split(".post", 1)[0]


def newest_release_per_base(data: dict) -> dict[str, str]:
    """Base CUDA_HISTORY version -> the newest released version it covers.

    RELEASES is maintained newest-first, so the first released entry that
    resolves to a base is the newest thing a reader can pull for that base's
    CUDA profile. Without this, a table keyed on CUDA_HISTORY names v0.7.0
    while v0.7.0.post1 is the newest release that actually runs there.
    """
    newest: dict[str, str] = {}
    for rel in data["RELEASES"]:
        if rel.get("kind") not in SUPPORT_MATRIX_KINDS:
            continue
        bare = rel["version"].removeprefix("v")
        newest.setdefault(post_train_base(bare), bare)
    return newest


def driver_floor_table(data: dict) -> str:
    """Driver floor -> the newest release each backend can run on that driver.

    Read a row as "if my driver is at least this version": a 580 driver also
    satisfies the 575 and 570 floors, so each cell is the newest release whose
    requirement that driver meets, not the newest release that requires
    exactly that floor.

    Floors and backends both come from CUDA_HISTORY, so a fourth floor or a
    fourth backend appears here the moment it is added to the data. Cells name
    the newest release including post trains, which inherit their base row.
    """
    versions = released_versions(data)
    newest_per_base = newest_release_per_base(data)
    rows = [row for row in data["CUDA_HISTORY"] if row["version"] in versions]
    if not rows:
        raise TSParseError(
            "no CUDA_HISTORY row matches a released RELEASES version -- the "
            "driver-floor table would render with no rows"
        )

    floors = sorted({parse_driver_floor(row["minDriver"]) for row in rows})
    backends = sorted({row["backend"] for row in rows})
    # CUDA_HISTORY is maintained newest-first, so the first matching row for a
    # backend is its newest release -- the same ordering the matrix relies on.
    labels = {parse_driver_floor(row["minDriver"]): row["minDriver"] for row in rows}

    table_rows = []
    for floor in floors:
        cells = [labels[floor]]
        for backend in backends:
            runnable = next(
                (
                    row["version"]
                    for row in rows
                    if row["backend"] == backend
                    and parse_driver_floor(row["minDriver"]) <= floor
                ),
                None,
            )
            cells.append(
                newest_per_base.get(runnable, runnable) if runnable else "None"
            )
        table_rows.append(cells)
    return md_table(["Driver", *backends], table_rows)


def render_driver_floors(data: dict) -> str:
    """The driver-first view of the support matrix.

    The matrix answers "what does this release need". A reader who already has
    a driver installed is asking the inverse, and answering it from the matrix
    means scanning every row for the floors their driver clears.
    """
    return "\n\n".join(
        [
            "Driver already installed? Read across from your version — each "
            "cell is the newest release that backend can run on it. A driver "
            "meeting a higher floor also runs everything below it.",
            driver_floor_table(data),
        ]
    )


def render_release_artifacts(data: dict) -> str:
    parts: list[str] = []
    parts.append(
        f"Current stable release: {data['CURRENT_VERSION']} "
        f"(container tag `{data['CURRENT_TAG']}`, wheel version `{data['CURRENT_WHEEL']}`)."
    )

    parts.append(f"**Artifact inventory ({data['CURRENT_VERSION']})**")
    parts.append(artifact_table(data))

    parts.append("**Known artifact issues**")
    parts.append(known_issues_table(data))

    if data.get("NIGHTLY_BUILDS"):
        parts.append("**Recent nightly wheel builds**")
        parts.append(nightlies_table(data))
        parts.append(data["NIGHTLIES_NOTE"])

    parts.append("**Crates: first published version on crates.io**")
    parts.append(crates_table(data))

    return "\n\n".join(parts)


def render_model_ea_builds(data: dict) -> str:
    parts: list[str] = []
    parts.append("**Model early-access builds**")
    parts.append(ea_table(data))
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# Dates (fixed mapping — content never depends on the wall clock)
# ---------------------------------------------------------------------------

_MONTHS = {
    "Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4, "May": 5, "Jun": 6,
    "Jul": 7, "Aug": 8, "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12,
}  # fmt: skip

_DATE_RE = re.compile(r"^([A-Z][a-z]{2}) (\d{1,2}), (\d{4})$")


def iso_date(human: str) -> str:
    """'Jul 20, 2026' -> '2026-07-20'. Fails closed on anything else."""
    m = _DATE_RE.match(human.strip())
    if not m or m.group(1) not in _MONTHS:
        raise TSParseError(f"unparseable date {human!r} (expected 'Mon D, YYYY')")
    return f"{int(m.group(3)):04d}-{_MONTHS[m.group(1)]:02d}-{int(m.group(2)):02d}"


def release_link(rel: dict) -> str | None:
    """Docs-native notes URL on the canonical prod host; GitHub fallback."""
    href = rel.get("notesHref")
    if href:
        return PROD_BASE + href.removeprefix("/dynamo")
    return rel.get("github")


# ---------------------------------------------------------------------------
# Machine-readable page (pages/reference/general/releases-machine-readable.mdx)
# ---------------------------------------------------------------------------


RELEASE_STATS_COLUMNS = (
    "Release",
    "PRs",
    "Contributors",
    "First-time contributors",
    "Breaking changes",
    "Known issues",
)


def release_stats_table(data: dict) -> str:
    """The release-statistics table, shared by both spans that render it.

    Release History shows it to readers and releases-data.mdx mirrors it for
    agents. Building both from here means the two cannot drift apart.
    """
    rows = [
        [
            version,
            stats.get("prs"),
            stats.get("contributors"),
            stats.get("firstTimers"),
            stats.get("breaking"),
            stats.get("knownIssues"),
        ]
        for version, stats in data["RELEASE_STATS"].items()
    ]
    return md_table(list(RELEASE_STATS_COLUMNS), rows)


def render_release_stats(data: dict) -> str:
    """Human-facing release statistics for the Release History page.

    Rows come from whatever RELEASE_STATS holds, so a new release picked up
    by the per-release bump checklist appears here with no edit to this file.
    """
    if not data.get("RELEASE_STATS"):
        raise TSParseError(
            "RELEASE_STATS is empty -- the release-statistics table on "
            "Release History would render with no rows"
        )
    return "\n\n".join(
        [
            "## Release statistics",
            "Counts taken from each release's GitHub body. A dash means the "
            "count was not recorded for that release, not that it was zero.",
            "The pre-v1.0.0 bodies predate the current release-note template "
            "and state no PR or contributor totals, so those cells stay empty: "
            "the figures were never published, and the counts recoverable from "
            "the archive and from git disagree with each other and with the "
            "totals the later bodies state. First-time contributors are "
            "counted release-wide; a release whose body lists only its "
            "external first-timers is left empty rather than undercounted.",
            release_stats_table(data),
        ]
    )


def render_releases_data(data: dict) -> str:
    """Full releases.data.ts content as plain markdown (not <llms-only>)."""
    parts: list[str] = []
    parts.append(
        f"Current stable release: {data['CURRENT_VERSION']} ({data['CURRENT_DATE']}; "
        f"container tag `{data['CURRENT_TAG']}`, wheel version `{data['CURRENT_WHEEL']}`)."
    )

    parts.append("## Releases")
    rel_rows: list[list] = []
    tot = data["MAIN_TOT"]
    rel_rows.append(
        [
            "main (ToT)",
            "development head",
            "-",
            tot.get("sglang"),
            tot.get("trtllm"),
            tot.get("vllm"),
            nixl_cell(tot),
            None,
            "-",
            "-",
        ]
    )
    for rel in data["RELEASES"]:
        pins = rel.get("pins") or {}
        link = release_link(rel)
        rel_rows.append(
            [
                rel["version"],
                rel.get("kind"),
                rel.get("date"),
                pins.get("sglang"),
                pins.get("trtllm"),
                pins.get("vllm"),
                nixl_cell(pins),
                rel.get("ucx"),
                f"[release notes]({link})" if link else None,
                rel.get("delta") or rel.get("note"),
            ]
        )
    parts.append(
        md_table(
            [
                "Version",
                "Kind",
                "Date",
                "SGLang",
                "TensorRT-LLM",
                "vLLM",
                "NIXL (SGL / TRT / vLLM)",
                "UCX",
                "Notes",
                "Delta",
            ],
            rel_rows,
        )
    )
    summaries = [
        f"- {rel['version']}: {rel['notesSummary']}"
        for rel in data["RELEASES"]
        if rel.get("notesSummary")
    ]
    if summaries:
        parts.append("Release highlights (stable releases):")
        parts.append("\n".join(summaries))

    parts.append("## CUDA toolkit and minimum driver history")
    parts.append(cuda_table(data))
    cuda_notes = data.get("CUDA_NOTES") or []
    if cuda_notes:
        parts.append("\n".join(f"- {note}" for note in cuda_notes))

    parts.append(f"## Feature support by backend ({data['CURRENT_VERSION']})")
    parts.append(feature_table(data))

    parts.append(f"## Artifact inventory ({data['CURRENT_VERSION']})")
    parts.append(artifact_table(data))

    parts.append("## Known artifact issues")
    parts.append(known_issues_table(data))

    parts.append("## Crates: first published version on crates.io")
    parts.append(crates_table(data))

    parts.append("## Model early-access builds")
    parts.append(ea_table(data))

    parts.append("## Platform-preview artifact coverage")
    ppc_rows = [
        [
            version,
            "yes" if cov.get("images") else "no",
            "yes" if cov.get("wheels") else "no",
            "yes" if cov.get("helm") else "no",
            "yes" if cov.get("crates") else "no",
        ]
        for version, cov in data["PLATFORM_PREVIEW_COVERAGE"].items()
    ]
    parts.append(md_table(["Preview", "Images", "Wheels", "Helm", "Crates"], ppc_rows))

    parts.append("## Platform support")
    parts.append(platform_lines(data))

    parts.append("## Release statistics")
    parts.append(release_stats_table(data))

    if data.get("NIGHTLIES_NOTE"):
        parts.append("## Nightlies")
        parts.append(data["NIGHTLIES_NOTE"])
        if data.get("NIGHTLY_BUILDS"):
            parts.append(nightlies_table(data))

    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# JSON payload (assets/releases.json)
# ---------------------------------------------------------------------------


def platform_payload(data: dict) -> dict:
    """PLATFORM with the retired ``status`` key restored for consumers.

    releases.data.ts renamed ``status`` to ``scope`` because "Supported" read
    the same on a shipped container base and on a wheels-only host. That rename
    is right for the page, but releases.json is a published asset with a stable
    schema: dropping a key breaks anything already reading
    ``platform.os[].status``. So the JSON carries both — ``scope`` as the
    precise field, ``status`` derived from it through SCOPE_STATUS. Deriving
    rather than defaulting is deliberate: the rows have not all carried
    "Supported" (the CentOS Stream row was "Experimental"), so an unmapped
    scope fails closed instead of publishing a support claim. ``status`` is
    deprecated; read ``scope``.
    """
    plat = {k: copy.deepcopy(v) for k, v in data["PLATFORM"].items()}
    for key in ("os", "csp"):
        for row in plat.get(key, []):
            if "scope" in row and "status" not in row:
                scope = row["scope"]
                if scope not in SCOPE_STATUS:
                    raise TSParseError(
                        f"unknown platform scope {scope!r}; add it to "
                        f"SCOPE_STATUS with the status it should publish"
                    )
                row["status"] = SCOPE_STATUS[scope]
    return plat


def build_json(data: dict) -> str:
    """Stable-schema JSON serialization of the parsed releases.data.ts."""
    releases = []
    for rel in data["RELEASES"]:
        out = dict(rel)
        if rel.get("date"):
            out["dateIso"] = iso_date(rel["date"])
        link = release_link(rel)
        if link:
            out["notesUrl"] = link
        releases.append(out)

    ea_builds = []
    for b in data["MODEL_EA_BUILDS"]:
        out = dict(b)
        out["shippedIso"] = iso_date(b["shipped"])
        ea_builds.append(out)

    nightly_builds = []
    for b in data.get("NIGHTLY_BUILDS", []):
        out = dict(b)
        out["dateIso"] = iso_date(b["date"])
        nightly_builds.append(out)

    if not any("dateIso" in r for r in releases):
        raise TSParseError("no dated RELEASES entries — cannot build releases.json")

    payload = {
        "source": "docs/fern/components/releases.data.ts",
        "generator": "docs/fern/scripts/gen_llms_tables.py",
        "updated": max(r["dateIso"] for r in releases if "dateIso" in r),
        "current": {
            "version": data["CURRENT_VERSION"],
            "date": data["CURRENT_DATE"],
            "dateIso": iso_date(data["CURRENT_DATE"]),
            "tag": data["CURRENT_TAG"],
            "wheel": data["CURRENT_WHEEL"],
        },
        "mainTot": data["MAIN_TOT"],
        "releases": releases,
        "cudaHistory": data["CUDA_HISTORY"],
        "cudaNotes": data.get("CUDA_NOTES") or [],
        "features": data["FEATURES"],
        "artifacts": data["ARTIFACTS"],
        "modelEaBuilds": ea_builds,
        "platformPreviewCoverage": data["PLATFORM_PREVIEW_COVERAGE"],
        "platform": platform_payload(data),
        "knownArtifactIssues": data["KNOWN_ARTIFACT_ISSUES"],
        "cratesFirstPublished": data["CRATES_FIRST_PUBLISHED"],
        "releaseStats": data["RELEASE_STATS"],
        "nightliesNote": data.get("NIGHTLIES_NOTE"),
        "nightlyBuilds": nightly_builds,
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# Atom feed (assets/releases-atom.xml)
# ---------------------------------------------------------------------------


def xml_escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def build_atom(data: dict) -> str:
    """Atom 1.0 feed of RELEASES, newest first, deterministic timestamps."""
    dated = []
    for index, rel in enumerate(data["RELEASES"]):
        if not rel.get("date"):
            continue  # undated entries cannot be ordered in a feed
        dated.append((iso_date(rel["date"]), index, rel))
    if not dated:
        raise TSParseError("no dated RELEASES entries — cannot build the Atom feed")
    # Newest first; ties keep releases.data.ts order (already newest-first).
    dated.sort(key=lambda item: (item[0], -item[1]), reverse=True)

    feed_updated = dated[0][0] + "T00:00:00Z"
    notes_index = f"{PROD_BASE}/dev/reference/releases"

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!--",
        "SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION"
        " & AFFILIATES. All rights reserved.",
        "SPDX-License-Identifier: Apache-2.0",
        "",
        "Generated by docs/fern/scripts/gen_llms_tables.py from"
        " docs/fern/components/releases.data.ts - do not edit.",
        "-->",
        '<feed xmlns="http://www.w3.org/2005/Atom">',
        "  <title>NVIDIA Dynamo releases</title>",
        f"  <id>{xml_escape(notes_index)}</id>",
        f'  <link rel="alternate" href="{xml_escape(notes_index)}"/>',
        f"  <updated>{feed_updated}</updated>",
        "  <author><name>NVIDIA Dynamo</name></author>",
    ]
    for date, _index, rel in dated:
        link = release_link(rel)
        entry_id = rel.get("github") or link
        if not entry_id or not link:
            raise TSParseError(
                f"release {rel['version']}: no notesHref or github link for the feed"
            )
        summary = rel.get("notesSummary") or rel.get("delta") or rel.get("note")
        lines += [
            "  <entry>",
            f"    <title>Dynamo {xml_escape(rel['version'])} ({xml_escape(rel['kind'])})</title>",
            f"    <id>{xml_escape(entry_id)}</id>",
            f'    <link rel="alternate" href="{xml_escape(link)}"/>',
            f"    <updated>{date}T00:00:00Z</updated>",
        ]
        if summary:
            lines.append(f"    <summary>{xml_escape(summary)}</summary>")
        lines.append("  </entry>")
    lines.append("</feed>")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Emission
# ---------------------------------------------------------------------------


class Block(NamedTuple):
    """One generated span in a page, delimited by ``<marker>:begin/:end``."""

    marker: str
    renderer: Callable[[dict], str]
    # Hide the body from human readers, leaving it only in agent exports.
    llms_only: bool
    # Append the span at end of file when the page has no markers yet.
    # False fails closed instead, so placement stays under human control.
    append_if_missing: bool


# The three component-backed pages get <llms-only> twins (humans see the React
# components); releases-machine-readable.mdx IS the page body, human-viewable
# and machine-consumable alike.
PAGES: dict[str, tuple[Block, ...]] = {
    "compatibility.mdx": (
        # The driver-floor table inverts the support matrix: read across from a
        # driver you already have to the newest release each backend can run on
        # it. <ReleaseSupportMatrix /> renders the forward view (release -> min
        # driver) and has no inverse mode, so this stays a generated span.
        Block("driver-floors", render_driver_floors, False, False),
        Block("llms-tables", render_compatibility, True, True),
    ),
    "release-artifacts.mdx": (
        Block("llms-tables", render_release_artifacts, True, True),
    ),
    "model-early-access-builds.mdx": (
        Block("llms-tables", render_model_ea_builds, True, True),
    ),
    "releases-machine-readable.mdx": (
        Block("llms-tables", render_releases_data, False, True),
    ),
    "releases/release-history.mdx": (
        Block("release-stats", render_release_stats, False, False),
    ),
}

# Scope to the support claim published in releases.json. Explicit rather than
# defaulting to "Supported": the rows have not always carried it -- the CentOS
# Stream row this PR removes was "Experimental" -- so a blanket default would
# publish a support claim for the next preview or restricted scope added here.
# Unmapped fails closed, like feature_cell and the interaction glyphs.
SCOPE_STATUS: dict[str, str] = {
    "Containers and wheels": "Supported",
    "Wheels only": "Supported",
}

# Standalone machine-readable outputs (path -> builder returning full text).
ASSET_OUTPUTS = {
    JSON_PATH: build_json,
    ATOM_PATH: build_atom,
}


def block_re(marker: str) -> re.Pattern[str]:
    """Match an existing generated span. Tolerant of edits to the note after
    "<marker>:begin" so a hand-tweaked marker comment is still replaced."""
    name = re.escape(marker)
    return re.compile(
        rf"\{{/\*\s*{name}:begin[^*]*\*/\}}.*?\{{/\*\s*{name}:end\s*\*/\}}",
        re.DOTALL,
    )


def build_block(block: Block, body: str) -> str:
    begin, end = marker_begin(block.marker), marker_end(block.marker)
    if block.llms_only:
        return f"{begin}\n<llms-only>\n\n{body}\n\n</llms-only>\n{end}"
    return f"{begin}\n\n{body}\n\n{end}"


def apply_block(page_text: str, block: Block, rendered: str) -> str:
    pattern = block_re(block.marker)
    if pattern.search(page_text):
        return pattern.sub(lambda _m: rendered, page_text, count=1)
    if not block.append_if_missing:
        raise TSParseError(
            f"{block.marker}: markers not found — the page must contain "
            f"{marker_begin(block.marker)} and {marker_end(block.marker)} "
            "where the generated span belongs"
        )
    # No markers yet: append at end of file, before the trailing newline.
    return page_text.rstrip("\n") + "\n\n" + rendered + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if regeneration would change a marker-spliced page; write nothing",
    )
    mode.add_argument(
        "--assets-only",
        action="store_true",
        help="write only assets/releases.json and assets/releases-atom.xml",
    )
    args = ap.parse_args(argv)

    try:
        data = parse_data_module(DATA_TS)
    except TSParseError as exc:
        print(f"error: failed to parse {DATA_TS}: {exc}", file=sys.stderr)
        return 2

    # Render every selected output up front so a rendering failure emits nothing.
    try:
        rendered: dict[Path, str] = {}
        if not args.assets_only:
            for page_name, blocks in PAGES.items():
                page_path = REFERENCE_DIR / page_name
                if not page_path.is_file():
                    print(f"error: page not found: {page_path}", file=sys.stderr)
                    return 2
                text = page_path.read_text(encoding="utf-8")
                for block in blocks:
                    body = build_block(block, block.renderer(data))
                    text = apply_block(text, block, body)
                rendered[page_path] = text
        if not args.check:
            for asset_path, builder in ASSET_OUTPUTS.items():
                rendered[asset_path] = builder(data)
    except (TSParseError, KeyError) as exc:
        print(f"error: rendering failed: {exc!r}", file=sys.stderr)
        return 2

    stale = []
    for path, new_text in rendered.items():
        # Relative to the reference root so pages in subdirectories are
        # distinguishable -- several are named README.mdx.
        name = (
            str(path.relative_to(REFERENCE_DIR))
            if path.is_relative_to(REFERENCE_DIR)
            else path.name
        )
        # Compare and write raw bytes: read_text() would normalize CRLF away,
        # letting a wrongly-encoded output pass as "unchanged" (and --check
        # as fresh) without ever being healed.
        old_bytes = path.read_bytes() if path.is_file() else None
        new_bytes = new_text.encode("utf-8")
        if new_bytes == old_bytes:
            print(f"{name}: unchanged")
            continue
        stale.append(name)
        if args.check:
            print(f"{name}: STALE (regeneration would change it)")
        else:
            path.write_bytes(new_bytes)
            print(f"{name}: wrote {len(new_bytes)} bytes")

    if args.check and stale:
        print(
            f"check failed: {len(stale)} output(s) stale — run gen_llms_tables.py",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
