#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Generate agent-facing twins of the Reference-page component data.

Three Reference pages (reference/compatibility.mdx,
reference/release-artifacts.mdx, reference/model-early-access-builds.mdx)
render their data through custom React components, whose output may be absent
from Fern's agent-facing markdown exports (.md endpoints, llms.txt). This
script reads the single source of truth ``components/releases.data.ts`` and
emits equivalent markdown tables into each page between idempotent markers,
wrapped in <llms-only> so only agent exports see them.

It also emits three machine-readable outputs from the same parse:

  * reference/releases-data.mdx — a "Releases (machine-readable)" page whose
    body (between the same idempotent markers, NOT <llms-only>-wrapped) is the
    full releases.data.ts content as plain markdown tables.
  * assets/releases.json — a stable-schema JSON serialization of the parsed
    data (current, mainTot, releases, cudaHistory, features, artifacts,
    modelEaBuilds, platform, releaseStats, ...). Human dates gain ISO-8601
    ``dateIso`` twins.
  * assets/releases-atom.xml — an Atom 1.0 feed, one entry per RELEASES item,
    newest first. Entry links resolve notesHref against the canonical prod
    base (https://docs.nvidia.com/dynamo), falling back to the GitHub release
    URL. The feed ``updated`` stamp is the newest release date (deterministic
    — never "now").

Usage (from any cwd; paths resolve relative to this file):

    python3 gen_llms_tables.py            # write/refresh all outputs
    python3 gen_llms_tables.py --check    # exit 1 if any output is stale, no writes

Re-run at every release bump, after editing releases.data.ts.

The parser is deliberately conservative: releases.data.ts must stay a
disciplined literal (see PARSER CONTRACT below). Any construct the parser
does not understand aborts the run with a clear error -- partial output is
never emitted.

PARSER CONTRACT (keep releases.data.ts within these bounds):
  * Top-level declarations of the form ``[export] const NAME[: Type] = <literal>;``
  * Literal values: object/array literals, string literals ('...' or "..."),
    template literals whose only interpolations are ``${IDENT}`` where IDENT
    is a previously declared string const (e.g. ``${GH}``, ``${NGC_C}``),
    numbers, true/false/null, and bare identifier references to previously
    declared consts (e.g. ``coverage: MODEL_COVERAGE``).
  * Object keys: bare identifiers or quoted strings.
  * No computed values, spreads, function calls, arithmetic, or ternaries.
"""

from __future__ import annotations

import argparse
import copy
import json
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DATA_TS = SCRIPT_DIR.parent / "components" / "releases.data.ts"
REFERENCE_DIR = SCRIPT_DIR.parent / "reference"
ASSETS_DIR = SCRIPT_DIR.parent / "assets"
JSON_PATH = ASSETS_DIR / "releases.json"
ATOM_PATH = ASSETS_DIR / "releases-atom.xml"

# Canonical prod host; notesHref values are absolute site paths (/dynamo/...).
PROD_HOST = "https://docs.nvidia.com"
PROD_BASE = f"{PROD_HOST}/dynamo"

MARKER_BEGIN = (
    "{/* llms-tables:begin — generated by scripts/gen_llms_tables.py, do not edit */}"
)
MARKER_END = "{/* llms-tables:end */}"

# Exports the generator depends on. Parsing aborts if any is missing.
REQUIRED_EXPORTS = [
    "RELEASES",
    "MAIN_TOT",
    "CURRENT_VERSION",
    "CURRENT_DATE",
    "CURRENT_TAG",
    "CURRENT_WHEEL",
    "CUDA_HISTORY",
    "FEATURES",
    "ARTIFACTS",
    "MODEL_EA_BUILDS",
    "PLATFORM",
    "PLATFORM_PREVIEW_COVERAGE",
    "KNOWN_ARTIFACT_ISSUES",
    "CRATES_FIRST_PUBLISHED",
    "RELEASE_STATS",
]


class TSParseError(Exception):
    """releases.data.ts contains a construct the conservative parser rejects."""


# ---------------------------------------------------------------------------
# TypeScript literal parsing (stdlib only, no TS runtime)
# ---------------------------------------------------------------------------


def strip_comments(src: str) -> str:
    """Remove // and /* */ comments, preserving string/template contents.

    A character walk (not regex) so that ``https://...`` inside strings and
    comment-like sequences inside template literals survive intact.
    """
    out: list[str] = []
    i, n = 0, len(src)
    while i < n:
        c = src[i]
        if c in "\"'`":
            quote = c
            out.append(c)
            i += 1
            while i < n:
                ch = src[i]
                out.append(ch)
                if ch == "\\" and i + 1 < n:  # keep escaped char verbatim
                    out.append(src[i + 1])
                    i += 2
                    continue
                i += 1
                if ch == quote:
                    break
            continue
        if c == "/" and i + 1 < n and src[i + 1] == "/":
            while i < n and src[i] != "\n":
                i += 1
            continue
        if c == "/" and i + 1 < n and src[i + 1] == "*":
            end = src.find("*/", i + 2)
            if end == -1:
                raise TSParseError("unterminated /* */ comment")
            # Preserve newlines so any future error positions stay meaningful.
            out.append("\n" * src.count("\n", i, end))
            i = end + 2
            continue
        out.append(c)
        i += 1
    return "".join(out)


class LiteralParser:
    """Recursive-descent parser for disciplined TS object/array literals."""

    def __init__(self, src: str, env: dict):
        self.src = src
        self.i = 0
        self.env = env  # previously parsed consts, for ${IDENT} / bare refs

    def error(self, msg: str) -> TSParseError:
        line = self.src.count("\n", 0, self.i) + 1
        context = self.src[self.i : self.i + 40].replace("\n", "\\n")
        return TSParseError(f"{msg} (near line {line}: {context!r})")

    def ws(self) -> None:
        while self.i < len(self.src) and self.src[self.i] in " \t\r\n":
            self.i += 1

    def peek(self) -> str:
        return self.src[self.i] if self.i < len(self.src) else ""

    def expect(self, ch: str) -> None:
        if self.peek() != ch:
            raise self.error(f"expected {ch!r}")
        self.i += 1

    def parse_value(self):
        self.ws()
        c = self.peek()
        if c == "{":
            return self.parse_object()
        if c == "[":
            return self.parse_array()
        if c in "\"'":
            return self.parse_string(c)
        if c == "`":
            return self.parse_template()
        if c.isdigit() or c == "-":
            return self.parse_number()
        if c.isalpha() or c == "_":
            return self.parse_word()
        raise self.error("unexpected token")

    def parse_object(self) -> dict:
        self.expect("{")
        obj: dict = {}
        while True:
            self.ws()
            if self.peek() == "}":
                self.i += 1
                return obj
            key = self.parse_key()
            self.ws()
            self.expect(":")
            obj[key] = self.parse_value()
            self.ws()
            if self.peek() == ",":
                self.i += 1
            elif self.peek() != "}":
                raise self.error("expected ',' or '}' in object")

    def parse_key(self) -> str:
        c = self.peek()
        if c in "\"'":
            return self.parse_string(c)
        m = re.match(r"[A-Za-z_$][\w$]*", self.src[self.i :])
        if not m:
            raise self.error("expected object key")
        self.i += m.end()
        return m.group(0)

    def parse_array(self) -> list:
        self.expect("[")
        arr: list = []
        while True:
            self.ws()
            if self.peek() == "]":
                self.i += 1
                return arr
            arr.append(self.parse_value())
            self.ws()
            if self.peek() == ",":
                self.i += 1
            elif self.peek() != "]":
                raise self.error("expected ',' or ']' in array")

    def parse_string(self, quote: str) -> str:
        self.expect(quote)
        out: list[str] = []
        while True:
            if self.i >= len(self.src):
                raise self.error("unterminated string")
            c = self.src[self.i]
            if c == "\\":
                out.append(self.unescape())
                continue
            self.i += 1
            if c == quote:
                return "".join(out)
            out.append(c)

    def parse_template(self) -> str:
        """Template literal; only ``${IDENT}`` interpolations of known
        string consts are allowed (the ``${GH}`` / ``${NGC_C}`` prefixes)."""
        self.expect("`")
        out: list[str] = []
        while True:
            if self.i >= len(self.src):
                raise self.error("unterminated template literal")
            c = self.src[self.i]
            if c == "\\":
                out.append(self.unescape())
                continue
            if c == "`":
                self.i += 1
                return "".join(out)
            if c == "$" and self.src[self.i : self.i + 2] == "${":
                m = re.match(r"\$\{([A-Za-z_$][\w$]*)\}", self.src[self.i :])
                if not m:
                    raise self.error("only ${IDENT} interpolation is supported")
                name = m.group(1)
                if name not in self.env or not isinstance(self.env[name], str):
                    raise self.error(
                        f"${{{name}}}: not a previously declared string const"
                    )
                out.append(self.env[name])
                self.i += m.end()
                continue
            out.append(c)
            self.i += 1

    def unescape(self) -> str:
        esc = self.src[self.i + 1] if self.i + 1 < len(self.src) else ""
        self.i += 2
        return {"n": "\n", "t": "\t", "r": "\r"}.get(esc, esc)

    def parse_number(self):
        m = re.match(r"-?\d+(?:\.\d+)?", self.src[self.i :])
        if not m:
            raise self.error("bad number")
        self.i += m.end()
        text = m.group(0)
        return float(text) if "." in text else int(text)

    def parse_word(self):
        m = re.match(r"[A-Za-z_$][\w$]*", self.src[self.i :])
        word = m.group(0)
        self.i += m.end()
        if word == "true":
            return True
        if word == "false":
            return False
        if word in ("null", "undefined"):
            return None
        # Bare identifier reference to a previously declared const
        # (e.g. ``coverage: MODEL_COVERAGE``). Deep-copied so shared
        # references never alias each other in the parsed data.
        if word in self.env:
            return copy.deepcopy(self.env[word])
        raise self.error(f"unknown identifier {word!r}")


DECL_RE = re.compile(
    r"^\s*(?:export\s+)?const\s+([A-Za-z_$][\w$]*)\s*(?::[^=;]+?)?=",
    re.MULTILINE,
)


def parse_data_module(path: Path) -> dict:
    """Parse every top-level const in releases.data.ts into a dict."""
    try:
        src = strip_comments(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise TSParseError(f"cannot read {path}: {exc}") from exc

    env: dict = {}
    for m in DECL_RE.finditer(src):
        name = m.group(1)
        parser = LiteralParser(src, env)
        parser.i = m.end()
        try:
            env[name] = parser.parse_value()
        except TSParseError as exc:
            raise TSParseError(f"while parsing const {name}: {exc}") from exc
        parser.ws()
        if parser.peek() == ";":
            parser.i += 1

    missing = [n for n in REQUIRED_EXPORTS if n not in env]
    if missing:
        raise TSParseError(f"missing required exports: {', '.join(missing)}")
    return env


# ---------------------------------------------------------------------------
# Markdown rendering
# ---------------------------------------------------------------------------


def cell(value) -> str:
    """Sanitize a value for a markdown table cell."""
    if value is None or value == "":
        return "-"
    return str(value).replace("|", "\\|").replace("\n", " ")


def md_table(headers: list[str], rows: list[list]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell(v) for v in row) + " |")
    return "\n".join(lines)


def nixl_cell(pins: dict) -> str:
    parts = [pins.get(k) or "-" for k in ("nixlSglang", "nixlTrtllm", "nixlVllm")]
    return " / ".join(parts) if any(p != "-" for p in parts) else "-"


FEATURE_STATUS_LABEL = {
    "yes": "Supported",
    "caveat": "Supported with caveat",
    "wip": "Experimental",
    "no": "Not supported",
}


def feature_cell(fc: dict) -> str:
    status = fc.get("status")
    if status not in FEATURE_STATUS_LABEL:
        raise TSParseError(f"unknown feature status {status!r}")
    label = FEATURE_STATUS_LABEL[status]
    note = fc.get("note")
    return f"{label} ({note})" if note else label


# ---------------------------------------------------------------------------
# Shared section renderers (composed by both the per-page <llms-only> twins
# and the machine-readable releases-data.mdx page; each returns a headerless
# fragment so every call site can supply its own heading style).
# ---------------------------------------------------------------------------


def cuda_table(data: dict) -> str:
    """CUDA toolkit and minimum-driver history table."""
    rows = [
        [r["version"], r["backend"], r["toolkit"], r["minDriver"], r.get("note")]
        for r in data["CUDA_HISTORY"]
    ]
    return md_table(["Dynamo", "Backend", "CUDA Toolkit", "Min Driver", "Note"], rows)


def feature_table(data: dict) -> str:
    """Feature-support-by-backend table."""
    rows = [
        [
            f["name"],
            feature_cell(f["sglang"]),
            feature_cell(f["trtllm"]),
            feature_cell(f["vllm"]),
        ]
        for f in data["FEATURES"]
    ]
    return md_table(["Feature", "SGLang", "TensorRT-LLM", "vLLM"], rows)


def artifact_table(data: dict) -> str:
    """Artifact-inventory table."""
    rows: list[list] = []
    for art in data["ARTIFACTS"]:
        name = art["name"]
        if art.get("badge"):
            name = f"{name} ({art['badge']})"
        tags = "; ".join(f"`{t['clipboard']}`" for t in art.get("tags", []))
        rows.append([art["category"], name, art["description"], art.get("meta"), tags])
    return md_table(["Category", "Name", "Description", "Meta", "Tags / install"], rows)


def known_issues_table(data: dict) -> str:
    """Known-artifact-issues table."""
    rows = [
        [i["version"], i["artifact"], i["issue"], i["status"]]
        for i in data["KNOWN_ARTIFACT_ISSUES"]
    ]
    return md_table(["Release", "Artifact", "Issue", "Status"], rows)


def crates_table(data: dict) -> str:
    """First-published-version-on-crates.io table."""
    rows = [
        [c["crate"], c["version"], c["date"]] for c in data["CRATES_FIRST_PUBLISHED"]
    ]
    return md_table(["Crate", "First version", "Date"], rows)


def platform_lines(data: dict) -> str:
    """Platform-support bullet lines (GPUs / OS / CSP / CPU arch / wheels)."""
    plat = data["PLATFORM"]
    lines = [f"- GPU architectures: {', '.join(plat['gpus'])}"]
    for os_row in plat["os"]:
        lines.append(
            f"- OS: {os_row['name']} {os_row['version']} ({os_row['arch']}) — {os_row['status']}"
        )
    for csp in plat.get("csp", []):
        lines.append(
            f"- CSP: {csp['provider']} — {csp['os']} ({csp['arch']}) — {csp['status']}"
        )
    lines.append(f"- CPU architectures: {', '.join(plat['arch'])}")
    if plat.get("wheelsNote"):
        lines.append(f"- Wheels: {plat['wheelsNote']}")
    return "\n".join(lines)


def ea_table(data: dict) -> str:
    """Model early-access builds table."""
    rows: list[list] = []
    for b in data["MODEL_EA_BUILDS"]:
        cov = b["coverage"]
        cov_cell = " / ".join(
            "yes" if cov.get(k) else "no"
            for k in ("images", "wheels", "helm", "crates")
        )
        rows.append(
            [
                b["model"],
                f"`{b['tag']}`",
                b["releaseLine"],
                ", ".join(b["runtimes"]),
                b["shipped"],
                b["gaLabel"],
                b["statusLine"],
                cov_cell,
            ]
        )
    return md_table(
        [
            "Model",
            "Tag",
            "Release line",
            "Runtimes",
            "Shipped",
            "GA path",
            "Status",
            "Coverage (images / wheels / helm / crates)",
        ],
        rows,
    )


def render_compatibility(data: dict) -> str:
    parts: list[str] = []
    parts.append(
        f"Current stable release: {data['CURRENT_VERSION']} "
        f"(container tag `{data['CURRENT_TAG']}`, wheel version `{data['CURRENT_WHEEL']}`)."
    )

    # Backend pins: main (ToT) first, then every tracked release, newest first.
    pin_rows: list[list] = []
    tot = data["MAIN_TOT"]
    pin_rows.append(
        [
            "main (ToT)",
            "development head",
            tot.get("sglang"),
            tot.get("trtllm"),
            tot.get("vllm"),
            nixl_cell(tot),
            None,
        ]
    )
    for rel in data["RELEASES"]:
        pins = rel.get("pins") or {}
        pin_rows.append(
            [
                rel["version"],
                rel.get("kind"),
                pins.get("sglang"),
                pins.get("trtllm"),
                pins.get("vllm"),
                nixl_cell(pins),
                rel.get("ucx"),
            ]
        )
    parts.append("**Backend engine pins per Dynamo release**")
    parts.append(
        md_table(
            [
                "Dynamo",
                "Type",
                "SGLang",
                "TensorRT-LLM",
                "vLLM",
                "NIXL (SGL / TRT / vLLM)",
                "UCX",
            ],
            pin_rows,
        )
    )

    parts.append("**CUDA toolkit and minimum driver per Dynamo release**")
    parts.append(cuda_table(data))
    cuda_notes = data.get("CUDA_NOTES") or []
    if cuda_notes:
        parts.append("\n".join(f"- {note}" for note in cuda_notes))

    parts.append(f"**Feature support by backend ({data['CURRENT_VERSION']})**")
    parts.append(feature_table(data))

    # Platform support (GPUs / OS / arch) — rendered by CompatibilityHero.
    parts.append("**Platform support**")
    parts.append(platform_lines(data))

    return "\n\n".join(parts)


def render_release_artifacts(data: dict) -> str:
    parts: list[str] = []
    parts.append(
        f"Current stable release: {data['CURRENT_VERSION']} "
        f"(container tag `{data['CURRENT_TAG']}`, wheel version `{data['CURRENT_WHEEL']}`)."
    )

    parts.append(f"**Artifact inventory ({data['CURRENT_VERSION']})**")
    parts.append(artifact_table(data))

    parts.append("**Known artifact issues**")
    parts.append(known_issues_table(data))

    parts.append("**Crates: first published version on crates.io**")
    parts.append(crates_table(data))

    return "\n\n".join(parts)


def render_model_ea_builds(data: dict) -> str:
    parts: list[str] = []
    parts.append("**Model early-access builds**")
    parts.append(ea_table(data))
    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# Dates (fixed mapping — content never depends on the wall clock)
# ---------------------------------------------------------------------------

_MONTHS = {
    "Jan": 1, "Feb": 2, "Mar": 3, "Apr": 4, "May": 5, "Jun": 6,
    "Jul": 7, "Aug": 8, "Sep": 9, "Oct": 10, "Nov": 11, "Dec": 12,
}  # fmt: skip

_DATE_RE = re.compile(r"^([A-Z][a-z]{2}) (\d{1,2}), (\d{4})$")


def iso_date(human: str) -> str:
    """'Jul 20, 2026' -> '2026-07-20'. Fails closed on anything else."""
    m = _DATE_RE.match(human.strip())
    if not m or m.group(1) not in _MONTHS:
        raise TSParseError(f"unparseable date {human!r} (expected 'Mon D, YYYY')")
    return f"{int(m.group(3)):04d}-{_MONTHS[m.group(1)]:02d}-{int(m.group(2)):02d}"


def release_link(rel: dict) -> str | None:
    """Docs-native notes URL on the canonical prod host; GitHub fallback."""
    href = rel.get("notesHref")
    if href:
        return PROD_BASE + href.removeprefix("/dynamo")
    return rel.get("github")


# ---------------------------------------------------------------------------
# Machine-readable page (reference/releases-data.mdx)
# ---------------------------------------------------------------------------


def render_releases_data(data: dict) -> str:
    """Full releases.data.ts content as plain markdown (not <llms-only>)."""
    parts: list[str] = []
    parts.append(
        f"Current stable release: {data['CURRENT_VERSION']} ({data['CURRENT_DATE']}; "
        f"container tag `{data['CURRENT_TAG']}`, wheel version `{data['CURRENT_WHEEL']}`)."
    )

    parts.append("## Releases")
    rel_rows: list[list] = []
    tot = data["MAIN_TOT"]
    rel_rows.append(
        [
            "main (ToT)",
            "development head",
            "-",
            tot.get("sglang"),
            tot.get("trtllm"),
            tot.get("vllm"),
            nixl_cell(tot),
            None,
            "-",
            "-",
        ]
    )
    for rel in data["RELEASES"]:
        pins = rel.get("pins") or {}
        link = release_link(rel)
        rel_rows.append(
            [
                rel["version"],
                rel.get("kind"),
                rel.get("date"),
                pins.get("sglang"),
                pins.get("trtllm"),
                pins.get("vllm"),
                nixl_cell(pins),
                rel.get("ucx"),
                f"[release notes]({link})" if link else None,
                rel.get("delta") or rel.get("note"),
            ]
        )
    parts.append(
        md_table(
            [
                "Version",
                "Kind",
                "Date",
                "SGLang",
                "TensorRT-LLM",
                "vLLM",
                "NIXL (SGL / TRT / vLLM)",
                "UCX",
                "Notes",
                "Delta",
            ],
            rel_rows,
        )
    )
    summaries = [
        f"- {rel['version']}: {rel['notesSummary']}"
        for rel in data["RELEASES"]
        if rel.get("notesSummary")
    ]
    if summaries:
        parts.append("Release highlights (stable releases):")
        parts.append("\n".join(summaries))

    parts.append("## CUDA toolkit and minimum driver history")
    parts.append(cuda_table(data))
    cuda_notes = data.get("CUDA_NOTES") or []
    if cuda_notes:
        parts.append("\n".join(f"- {note}" for note in cuda_notes))

    parts.append(f"## Feature support by backend ({data['CURRENT_VERSION']})")
    parts.append(feature_table(data))

    parts.append(f"## Artifact inventory ({data['CURRENT_VERSION']})")
    parts.append(artifact_table(data))

    parts.append("## Known artifact issues")
    parts.append(known_issues_table(data))

    parts.append("## Crates: first published version on crates.io")
    parts.append(crates_table(data))

    parts.append("## Model early-access builds")
    parts.append(ea_table(data))

    parts.append("## Platform-preview artifact coverage")
    ppc_rows = [
        [
            version,
            "yes" if cov.get("images") else "no",
            "yes" if cov.get("wheels") else "no",
            "yes" if cov.get("helm") else "no",
            "yes" if cov.get("crates") else "no",
        ]
        for version, cov in data["PLATFORM_PREVIEW_COVERAGE"].items()
    ]
    parts.append(md_table(["Preview", "Images", "Wheels", "Helm", "Crates"], ppc_rows))

    parts.append("## Platform support")
    parts.append(platform_lines(data))

    parts.append("## Release statistics")
    stat_rows = [
        [
            version,
            stats.get("prs"),
            stats.get("contributors"),
            stats.get("firstTimers"),
            stats.get("breaking"),
            stats.get("knownIssues"),
        ]
        for version, stats in data["RELEASE_STATS"].items()
    ]
    parts.append(
        md_table(
            [
                "Release",
                "PRs",
                "Contributors",
                "First-time contributors",
                "Breaking changes",
                "Known issues",
            ],
            stat_rows,
        )
    )

    if data.get("NIGHTLIES_NOTE"):
        parts.append("## Nightlies")
        parts.append(data["NIGHTLIES_NOTE"])

    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# JSON payload (assets/releases.json)
# ---------------------------------------------------------------------------


def build_json(data: dict) -> str:
    """Stable-schema JSON serialization of the parsed releases.data.ts."""
    releases = []
    for rel in data["RELEASES"]:
        out = dict(rel)
        if rel.get("date"):
            out["dateIso"] = iso_date(rel["date"])
        link = release_link(rel)
        if link:
            out["notesUrl"] = link
        releases.append(out)

    ea_builds = []
    for b in data["MODEL_EA_BUILDS"]:
        out = dict(b)
        out["shippedIso"] = iso_date(b["shipped"])
        ea_builds.append(out)

    if not any("dateIso" in r for r in releases):
        raise TSParseError("no dated RELEASES entries — cannot build releases.json")

    payload = {
        "source": "docs/fern/components/releases.data.ts",
        "generator": "docs/fern/scripts/gen_llms_tables.py",
        "updated": max(r["dateIso"] for r in releases if "dateIso" in r),
        "current": {
            "version": data["CURRENT_VERSION"],
            "date": data["CURRENT_DATE"],
            "dateIso": iso_date(data["CURRENT_DATE"]),
            "tag": data["CURRENT_TAG"],
            "wheel": data["CURRENT_WHEEL"],
        },
        "mainTot": data["MAIN_TOT"],
        "releases": releases,
        "cudaHistory": data["CUDA_HISTORY"],
        "cudaNotes": data.get("CUDA_NOTES") or [],
        "features": data["FEATURES"],
        "artifacts": data["ARTIFACTS"],
        "modelEaBuilds": ea_builds,
        "platformPreviewCoverage": data["PLATFORM_PREVIEW_COVERAGE"],
        "platform": data["PLATFORM"],
        "knownArtifactIssues": data["KNOWN_ARTIFACT_ISSUES"],
        "cratesFirstPublished": data["CRATES_FIRST_PUBLISHED"],
        "releaseStats": data["RELEASE_STATS"],
        "nightliesNote": data.get("NIGHTLIES_NOTE"),
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# Atom feed (assets/releases-atom.xml)
# ---------------------------------------------------------------------------


def xml_escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def build_atom(data: dict) -> str:
    """Atom 1.0 feed of RELEASES, newest first, deterministic timestamps."""
    dated = []
    for index, rel in enumerate(data["RELEASES"]):
        if not rel.get("date"):
            continue  # undated entries cannot be ordered in a feed
        dated.append((iso_date(rel["date"]), index, rel))
    if not dated:
        raise TSParseError("no dated RELEASES entries — cannot build the Atom feed")
    # Newest first; ties keep releases.data.ts order (already newest-first).
    dated.sort(key=lambda item: (item[0], -item[1]), reverse=True)

    feed_updated = dated[0][0] + "T00:00:00Z"
    notes_index = f"{PROD_BASE}/dev/reference/releases/release-history"

    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!--",
        "SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION"
        " & AFFILIATES. All rights reserved.",
        "SPDX-License-Identifier: Apache-2.0",
        "",
        "Generated by docs/fern/scripts/gen_llms_tables.py from"
        " docs/fern/components/releases.data.ts - do not edit.",
        "-->",
        '<feed xmlns="http://www.w3.org/2005/Atom">',
        "  <title>NVIDIA Dynamo releases</title>",
        f"  <id>{xml_escape(notes_index)}</id>",
        f'  <link rel="alternate" href="{xml_escape(notes_index)}"/>',
        f"  <updated>{feed_updated}</updated>",
        "  <author><name>NVIDIA Dynamo</name></author>",
    ]
    for date, _index, rel in dated:
        link = release_link(rel)
        entry_id = rel.get("github") or link
        if not entry_id or not link:
            raise TSParseError(
                f"release {rel['version']}: no notesHref or github link for the feed"
            )
        summary = rel.get("notesSummary") or rel.get("delta") or rel.get("note")
        lines += [
            "  <entry>",
            f"    <title>Dynamo {xml_escape(rel['version'])} ({xml_escape(rel['kind'])})</title>",
            f"    <id>{xml_escape(entry_id)}</id>",
            f'    <link rel="alternate" href="{xml_escape(link)}"/>',
            f"    <updated>{date}T00:00:00Z</updated>",
        ]
        if summary:
            lines.append(f"    <summary>{xml_escape(summary)}</summary>")
        lines.append("  </entry>")
    lines.append("</feed>")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Emission
# ---------------------------------------------------------------------------

# page -> (renderer, wrap_in_llms_only). The three component-backed pages get
# <llms-only> twins (humans see the React components); releases-data.mdx IS
# the page body, human-viewable and machine-consumable alike.
PAGES = {
    "compatibility.mdx": (render_compatibility, True),
    "release-artifacts.mdx": (render_release_artifacts, True),
    "model-early-access-builds.mdx": (render_model_ea_builds, True),
    "releases-data.mdx": (render_releases_data, False),
}

# Standalone machine-readable outputs (path -> builder returning full text).
ASSET_OUTPUTS = {
    JSON_PATH: build_json,
    ATOM_PATH: build_atom,
}

# Matches an existing generated span. Tolerant of edits to the note after
# "llms-tables:begin" so a hand-tweaked marker comment is still replaced.
BLOCK_RE = re.compile(
    r"\{/\*\s*llms-tables:begin[^*]*\*/\}.*?\{/\*\s*llms-tables:end\s*\*/\}",
    re.DOTALL,
)


def build_block(body: str, wrap: bool = True) -> str:
    if wrap:
        return f"{MARKER_BEGIN}\n<llms-only>\n\n{body}\n\n</llms-only>\n{MARKER_END}"
    return f"{MARKER_BEGIN}\n\n{body}\n\n{MARKER_END}"


def apply_block(page_text: str, block: str) -> str:
    if BLOCK_RE.search(page_text):
        return BLOCK_RE.sub(lambda _m: block, page_text, count=1)
    # No markers yet: append at end of file, before the trailing newline.
    return page_text.rstrip("\n") + "\n\n" + block + "\n"


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if regeneration would change any page; write nothing",
    )
    args = ap.parse_args(argv)

    try:
        data = parse_data_module(DATA_TS)
    except TSParseError as exc:
        print(f"error: failed to parse {DATA_TS}: {exc}", file=sys.stderr)
        return 2

    # Render everything up front so a failure on any output emits nothing.
    try:
        rendered: dict[Path, str] = {}
        for page_name, (renderer, wrap) in PAGES.items():
            page_path = REFERENCE_DIR / page_name
            if not page_path.is_file():
                print(f"error: page not found: {page_path}", file=sys.stderr)
                return 2
            old = page_path.read_text(encoding="utf-8")
            rendered[page_path] = apply_block(old, build_block(renderer(data), wrap))
        for asset_path, builder in ASSET_OUTPUTS.items():
            rendered[asset_path] = builder(data)
    except (TSParseError, KeyError) as exc:
        print(f"error: rendering failed: {exc!r}", file=sys.stderr)
        return 2

    stale = []
    for path, new_text in rendered.items():
        name = path.name
        old_text = path.read_text(encoding="utf-8") if path.is_file() else None
        if new_text == old_text:
            print(f"{name}: unchanged")
            continue
        stale.append(name)
        if args.check:
            print(f"{name}: STALE (regeneration would change it)")
        else:
            path.write_text(new_text, encoding="utf-8")
            print(f"{name}: wrote {len(new_text.encode('utf-8'))} bytes")

    if args.check and stale:
        print(
            f"check failed: {len(stale)} output(s) stale — run gen_llms_tables.py",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
