# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Deterministic MDX rendering for the Dynamo Kubernetes API reference.

Consumes the discovered :class:`~kubernetes_api_discovery.KubernetesReference`
model and produces one MDX page built from Fern's own components:
``<CardGroup>`` / ``<Card>`` for each package's resource-type entry points,
``<AccordionGroup>`` / ``<Accordion>`` per documented type, ``<ParamField>``
per schema field, and ``<Badge>`` per enum value. This matches the pattern the
backend config references already use, so the schema is searchable while
collapsed and Fern derives the Markdown and llms.txt twins itself.

No I/O happens in this module -- callers own the writes. Identical inputs
must produce byte-identical outputs so ``--check`` and diff review stay
reliable.
"""

from __future__ import annotations

import re
from collections.abc import Iterable

from kubernetes_api_discovery import (
    KubernetesEnumValue,
    KubernetesField,
    KubernetesPackage,
    KubernetesReference,
    KubernetesType,
    OperatorDefaults,
)
from markdown_rendering import escape_mdx_prose
from markdown_rendering import mdx_attribute as _attr

MDX_GENERATED_MARKER = (
    "{/* GENERATED by docs/fern/scripts/gen_kubernetes_api.py -- do not edit. */}"
)
LOCAL_FRAGMENT_LINK_RE = re.compile(r"\[(?P<label>[^\]]+)\]\(#(?P<anchor>[^)]+)\)")
MARKDOWN_LINK_RE = re.compile(r"\[(?P<label>[^\]]+)\]\((?P<target>[^)]+)\)")
# crd-ref-docs preserves the hard line wraps of the Go doc comments as
# literal ``<br />`` markers. Those wraps are ~80-column source formatting,
# not authored line breaks, so keeping them would break sentences at
# arbitrary points -- and escape_mdx_prose escapes the marker, surfacing
# ``&lt;br /&gt;`` to the reader. Collapse them to a space, which is what
# escape_mdx_table_cell already does for the same source text.
BR_RE = re.compile(r"<br\s*/?>")
# Repo paths, not links: this page, its generator, and the raw Markdown all
# land in the same change, so a github.com/.../blob/main deep link to any of
# them 404s until that change merges and fails the link checker.
SOURCE_PATH_MD = (
    "docs/fern/pages/reference/kubernetes-api/additional-resources/api-reference-k8s.md"
)
GENERATOR_PATH = "docs/fern/scripts/gen_kubernetes_api.py"

_FRONTMATTER = (
    "---\n"
    "# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION "
    "& AFFILIATES. All rights reserved.\n"
    "# SPDX-License-Identifier: Apache-2.0\n"
    "title: API Reference\n"
    "subtitle: Full Kubernetes CRD + operator-config API reference, generated "
    "from the operator Go types.\n"
    "---\n"
)

_WARNING = (
    "> [!WARNING]\n"
    "> **Auto-generated from source.** This page is regenerated from the "
    f"Dynamo operator CRDs by `{GENERATOR_PATH}` and covers "
    "**every** type across all three API packages: the deprecated "
    "`nvidia.com/v1alpha1` surface, the supported `nvidia.com/v1beta1` surface, "
    "and the operator's own `operator.config.dynamo.nvidia.com/v1alpha1` "
    "configuration. The trimmed "
    "[DGD](dynamo-graph-deployment.mdx), "
    "[DGDR](dynamo-graph-deployment-request.mdx), and "
    "[DCD](dynamo-component-deployment.mdx) references cover "
    "only user-facing `v1beta1` fields. To edit the surface, change the Go "
    "types under `deploy/operator/api/` and let CI regenerate this page.\n"
)


def _prose(text: str) -> str:
    """Escape crd-ref-docs prose for MDX, collapsing its ``<br />`` wraps."""
    return escape_mdx_prose(BR_RE.sub(" ", text))


def render_mdx(reference: KubernetesReference) -> str:
    """Full MDX text for the Kubernetes API reference page."""
    parts = [
        _FRONTMATTER.rstrip("\n"),
        "",
        MDX_GENERATED_MARKER,
        "",
        _WARNING.rstrip("\n"),
        "",
        _package_index(reference),
    ]
    for package in reference.packages:
        parts.append("")
        parts.append(_package_section(package))
    parts.append("")
    parts.append(_operator_defaults(reference.operator_defaults))
    parts.append("")
    parts.append(f"Raw generated Markdown source: `{SOURCE_PATH_MD}`")
    return "\n".join(parts).rstrip() + "\n"


def _package_index(reference: KubernetesReference) -> str:
    """Lead paragraph plus a jump card per API package."""
    total_types = sum(len(pkg.types) for pkg in reference.packages)
    lines = [
        f"Dynamo publishes {len(reference.packages)} Kubernetes API packages "
        f"with {total_types} typed CRD and config sections.",
        "",
        "<CardGroup cols={3}>",
    ]
    for pkg in reference.packages:
        lines.append(
            f'<Card title="{_attr(pkg.name)}" href="#{pkg.anchor}">'
            f"{len(pkg.types)} types</Card>"
        )
    lines.append("</CardGroup>")
    return "\n".join(lines)


def _package_section(package: KubernetesPackage) -> str:
    """One package heading, its resource-type cards, and every typed section."""
    valid_anchors = {type_.anchor for type_ in package.types}
    # A bare <div> target, not an <a>: package tables link to #anchor, but an
    # <a> with no text is an empty link to assistive tech.
    lines = [f'<div id="{_attr(package.anchor)}" />', "", f"## {package.name}"]
    if package.description:
        lines += ["", _prose(package.description)]
    if package.resource_types:
        lines += ["", "**Resource Types**", "", "<CardGroup cols={3}>"]
        for ref in package.resource_types:
            lines.append(f'<Card title="{_attr(ref.name)}" href="#{ref.anchor}" />')
        lines.append("</CardGroup>")
    for type_ in package.types:
        lines += ["", *_type_section(type_, valid_anchors)]
    return "\n".join(lines)


def _type_section(type_: KubernetesType, valid_anchors: set[str]) -> list[str]:
    """One anchored accordion carrying a type's full schema.

    Field tables across packages deep-link to ``#anchor``, and Accordion takes
    that id natively, so the collapsed body stays a reachable scroll target.
    """
    lines = [
        f'<Accordion id="{_attr(type_.anchor)}" title="{_attr(type_.display_name)}">',
    ]
    lines.extend(_type_body(type_, valid_anchors))
    lines.append("</Accordion>")
    return lines


def _type_body(type_: KubernetesType, valid_anchors: set[str]) -> list[str]:
    """Description, metadata lines, fields, and enum values for one type."""
    lines: list[str] = []
    if type_.description:
        lines += [_prose(type_.description), ""]
    lines.extend(_type_metadata(type_, valid_anchors))
    for field in type_.fields:
        lines += ["", *_param_field(field, valid_anchors)]
    if type_.enum_values:
        lines += ["", *_enum_values(type_.enum_values)]
    return lines


def _type_metadata(type_: KubernetesType, valid_anchors: set[str]) -> list[str]:
    """Kind, underlying type, validation, and back-references for one type."""
    lines = [f"**Kind:** `{type_.kind}`"]
    if type_.underlying_type:
        lines.append(f"**Underlying type:** `{_plain(type_.underlying_type)}`")
    if type_.validation:
        lines.append(f"**Validation:** {_prose(type_.validation)}")
    refs = [ref for ref in type_.appears_in if ref.anchor in valid_anchors]
    if refs:
        joined = ", ".join(f"[{ref.name}](#{ref.anchor})" for ref in refs)
        lines.append(f"**Appears in:** {joined}")
    return ["", *lines] if lines else lines


def _param_field(field: KubernetesField, valid_anchors: set[str]) -> list[str]:
    """One ``<ParamField>`` for a schema field.

    ``type`` carries the plain type name because MDX attributes cannot hold
    Markdown; when the source type linked to another documented type, the
    link is re-emitted in the body so navigation survives.
    """
    attrs = [f'path="{_attr(field.name)}"', f'type="{_attr(_plain(field.type))}"']
    if field.default:
        attrs.append(f'default="{_attr(field.default)}"')
    if field.required:
        attrs.append("required={true}")
    lines = [f"<ParamField {' '.join(attrs)}>"]
    if field.description:
        lines.append(_prose(field.description))
    lines.extend(_field_footnotes(field, valid_anchors))
    lines.append("</ParamField>")
    return lines


def _field_footnotes(field: KubernetesField, valid_anchors: set[str]) -> list[str]:
    """Resolved type links and validation notes for one field."""
    lines: list[str] = []
    links = _type_links(field.type, valid_anchors)
    if links:
        lines.append(f"See {', '.join(links)}.")
    if field.validation:
        lines.append(f"**Validation:** {_prose(field.validation)}")
    return lines


def _type_links(field_type: str, valid_anchors: set[str]) -> list[str]:
    """Links a field's type points at, dropping unresolvable local anchors.

    A same-page anchor only works if this page renders it; an absolute URL to
    the upstream Kubernetes API always resolves and is kept as-is.
    """
    links = []
    for match in MARKDOWN_LINK_RE.finditer(field_type):
        target = match.group("target")
        if target.startswith("#") and target.lstrip("#") not in valid_anchors:
            continue
        links.append(f"[{match.group('label')}]({target})")
    return links


def _enum_values(values: Iterable[KubernetesEnumValue]) -> list[str]:
    """Allowed-value badges plus their descriptions."""
    lines = ["**Allowed values**", ""]
    for value in values:
        badge = f'<Badge intent="note" minimal>{_prose(value.name)}</Badge>'
        description = _prose(value.description)
        lines.append(f"- {badge} {description}" if description else f"- {badge}")
    return lines


def _operator_defaults(defaults: OperatorDefaults) -> str:
    """Render the operator-defaults trailer with H2 to H3 heading demotion.

    The upstream Markdown treats the trailer as an H1 with H2 subsections.
    The page embeds it as an H2 with H3 subsections so the whole document
    nests consistently under the title Fern renders from the navigation.
    """
    parts = ["## Operator Default Values Injection", "", defaults.intro_markdown]
    for sub in defaults.subsections:
        parts.append("")
        parts.append(f"### {sub.title}")
        parts.append("")
        parts.append(_demote_headings(sub.body_markdown))
    return "\n".join(parts).rstrip() + "\n"


def _demote_headings(markdown: str) -> str:
    """Prepend one ``#`` to every ATX heading line in ``markdown``.

    Lines inside fenced code blocks (```` ``` ```` or ``~~~``) are passed
    through verbatim so ``#``-prefixed YAML or shell comments inside CRD
    examples are not rewritten. Existing H6 headings stay at H6 because
    ``#######`` is not a valid ATX heading and would render as literal
    text.
    """
    fence_char: str | None = None
    result: list[str] = []
    for line in markdown.splitlines():
        fence_open = _fence_delimiter(line)
        if fence_char is None:
            if fence_open is not None:
                fence_char = fence_open
                result.append(line)
                continue
            if _is_atx_heading(line) and _atx_level(line) < 6:
                result.append("#" + line)
            else:
                result.append(line)
        else:
            if fence_open is not None and fence_open == fence_char:
                fence_char = None
            result.append(line)
    return "\n".join(result)


def _fence_delimiter(line: str) -> str | None:
    """Return the fence character (``\\``` or ``~``) if ``line`` opens or
    closes a fenced code block, else ``None``.

    A fence is at least three consecutive fence characters at column 0 or
    after up to three spaces of leading indentation, matching CommonMark.
    """
    stripped = line.lstrip(" ")
    indent = len(line) - len(stripped)
    if indent > 3:
        return None
    for fence in ("`", "~"):
        if stripped.startswith(fence * 3):
            return fence
    return None


def _is_atx_heading(line: str) -> bool:
    """True when ``line`` is an ATX Markdown heading (``#``..``######``)."""
    return _atx_level(line) is not None


def _atx_level(line: str) -> int | None:
    """Return the ATX heading level (1..6) or ``None`` if ``line`` is not one."""
    stripped = line.lstrip()
    if not stripped.startswith("#"):
        return None
    prefix = stripped[: len(stripped) - len(stripped.lstrip("#"))]
    if len(prefix) < 1 or len(prefix) > 6:
        return None
    rest = stripped[len(prefix) :]
    if rest.startswith(" ") or rest == "":
        return len(prefix)
    return None


def _plain(text: str) -> str:
    """Replace every Markdown link with its label text.

    MDX attributes render no Markdown, so any link left in one shows up as
    mangled literal text. Upstream field types link both to sibling anchors and
    to the Kubernetes API docs, so both forms have to be flattened.
    """
    return MARKDOWN_LINK_RE.sub(lambda match: match.group("label"), text).strip()


__all__ = [
    "MDX_GENERATED_MARKER",
    "render_mdx",
]
