# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""Render deterministic native MDX for the Rust API reference."""

from __future__ import annotations

from markdown_rendering import escape_mdx_prose, escape_mdx_table_cell, mdx_attribute
from rust_api_discovery import RustBinding, RustCrate, RustReference

MDX_GENERATED_MARKER = (
    "{/* GENERATED by docs/fern/scripts/gen_rust_api.py -- do not edit. */}"
)
GROUP_LABELS = {
    "core": "Core Crates",
    "supporting": "Supporting Crates",
    "development": "Development and Testing",
    "deprecated": "Deprecated Crates",
}


def render_page(reference: RustReference) -> str:
    """Render the Rust API page from native Fern components and Markdown."""
    frontmatter = (
        "---\n"
        "# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION "
        "& AFFILIATES. All rights reserved.\n"
        "# SPDX-License-Identifier: Apache-2.0\n"
        "title: Rust API\n"
        "subtitle: Published Dynamo crates with release-pinned docs.rs links.\n"
        "---\n"
    )
    return f"{frontmatter}\n{MDX_GENERATED_MARKER}\n\n{_body_markdown(reference)}"


def _body_markdown(reference: RustReference) -> str:
    """Crate cards followed by grouped crate and binding tables."""
    parts = [
        f"Dynamo publishes {len(reference.crates)} Rust crates for "
        f"release `{reference.release_tag}`.",
        _crate_cards(reference.crates),
    ]
    for group, label in GROUP_LABELS.items():
        crates = [crate for crate in reference.crates if crate.group == group]
        if crates:
            parts.extend([f"## {label}", _crate_table(crates)])
    parts.extend(["## Language Bindings", _binding_table(reference.bindings)])
    return "\n\n".join(parts).rstrip() + "\n"


def _crate_cards(crates: tuple[RustCrate, ...]) -> str:
    """One navigation card per crate, linking to release-pinned docs.rs."""
    lines = ["<CardGroup cols={3}>"]
    for crate in crates:
        lines.append(
            f'<Card title="{mdx_attribute(crate.name)}" href="{crate.docs_href}">'
            f"{escape_mdx_prose(crate.summary)}</Card>"
        )
    lines.append("</CardGroup>")
    return "\n".join(lines)


def _crate_table(crates: list[RustCrate]) -> str:
    """Render one compact Markdown crate table."""
    rows = [
        "| Crate | Summary | Version | Install |",
        "| --- | --- | --- | --- |",
    ]
    for crate in crates:
        name = f"[`{crate.name}`]({crate.docs_href})"
        rows.append(
            f"| {name} | {_cell(crate.summary)} | `{crate.version}` | "
            f"`{crate.install_command}` |"
        )
    return "\n".join(rows)


def _binding_table(bindings: tuple[RustBinding, ...]) -> str:
    """Render the repository binding table."""
    rows = [
        "| Binding | Language | Summary | Source |",
        "| --- | --- | --- | --- |",
    ]
    for binding in bindings:
        source = f"[`{binding.member_path}`]({binding.source_href})"
        rows.append(
            f"| `{binding.name}` | {binding.language} | "
            f"{_cell(binding.summary)} | {source} |"
        )
    return "\n".join(rows)


def _cell(text: str) -> str:
    """Escape text for a Markdown table cell."""
    return escape_mdx_table_cell(text, empty="")
