# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: vllm-disagg-aws-efa
spec:
  services:
    PrefillWorker:
      extraPodSpec:
        mainContainer:
          env: &efaEnvironment
            - name: KV_TRANSFER_CONFIG
              value: '{"kv_connector":"NixlConnector","kv_role":"kv_both","kv_connector_extra_config":{"backends":["LIBFABRIC"]}}'
    DecodeWorker:
      extraPodSpec:
        mainContainer:
          env: *efaEnvironment
